import { db, now, genId, addAudit } from "./index";
import {
  users,
  roles,
  branches,
  donors,
  donations,
  projects,
  beneficiaries,
  aidRecords,
  accounts,
  journalEntries,
  costCenters,
  budgets,
  approvals,
  suppliers,
  purchaseRequests,
  purchaseOrders,
  quotes,
  inventoryItems,
  warehouses,
  campaigns,
  memberships,
  meetings,
  grants,
  endowments,
  fixedAssets,
  auditLog,
  receipts,
} from "./schema";
import { eq } from "drizzle-orm";

// Simple hash (demo - use bcrypt in production)
export function hashPassword(p: string) {
  return Buffer.from(p).toString("base64");
}

export function verifyPassword(p: string, h: string) {
  return Buffer.from(p).toString("base64") === h;
}

export async function seedDemoData() {
  // Check if already seeded
  const existingUsers = db.select().from(users).limit(1).all();
  if (existingUsers.length > 0) return;

  const ts = now();

  // ============ ROLES ============
  const rolesData = [
    {
      id: "role-admin",
      name: "مدير النظام",
      description: "صلاحيات كاملة",
      permissions: JSON.stringify(["*"]),
    },
    {
      id: "role-accountant",
      name: "محاسب",
      description: "محاسب مالي",
      permissions: JSON.stringify([
        "donations.view",
        "donations.create",
        "journal.view",
        "journal.create",
        "accounts.view",
        "reports.view",
      ]),
    },
    {
      id: "role-manager",
      name: "مدير",
      description: "مدير جمعية",
      permissions: JSON.stringify([
        "donations.*",
        "projects.*",
        "beneficiaries.*",
        "reports.*",
        "users.view",
        "finance.*",
      ]),
    },
    {
      id: "role-donations",
      name: "موظف تبرعات",
      description: "موظف قسم التبرعات",
      permissions: JSON.stringify(["donors.*", "donations.*", "receipts.*", "campaigns.*"]),
    },
    {
      id: "role-projects",
      name: "منسق مشاريع",
      description: "منسق ومتابعة مشاريع",
      permissions: JSON.stringify(["projects.*", "beneficiaries.*", "aid.*"]),
    },
  ];
  for (const r of rolesData)
    db.insert(roles)
      .values({ ...r, created_at: ts })
      .run();

  // ============ BRANCHES ============
  const branchesData = [
    {
      id: "BR-001",
      name: "الفرع الرئيسي - الرياض",
      city: "الرياض",
      manager: "سلطان العتيبي",
      phone: "0114567890",
      email: "riyadh@albir.org.sa",
      status: "نشط",
      created_at: ts,
    },
    {
      id: "BR-002",
      name: "فرع جدة",
      city: "جدة",
      manager: "نورة القحطاني",
      phone: "0126543210",
      email: "jeddah@albir.org.sa",
      status: "نشط",
      created_at: ts,
    },
    {
      id: "BR-003",
      name: "فرع الدمام",
      city: "الدمام",
      manager: "فهد الغامدي",
      phone: "0138234567",
      email: "dammam@albir.org.sa",
      status: "نشط",
      created_at: ts,
    },
  ];
  for (const b of branchesData) db.insert(branches).values(b).run();

  // ============ USERS ============
  const usersData = [
    {
      id: "USR-001",
      name: "سعد الغامدي",
      email: "saud@albir.org.sa",
      password: hashPassword("admin123"),
      role: "مدير النظام",
      branchId: "BR-001",
      status: "نشط",
      avatar: null,
      created_at: ts,
      last_login: ts,
    },
    {
      id: "USR-002",
      name: "سارة الزهراني",
      email: "sara@albir.org.sa",
      password: hashPassword("acc123"),
      role: "محاسب",
      branchId: "BR-001",
      status: "نشط",
      created_at: ts,
    },
    {
      id: "USR-003",
      name: "محمد الغامدي",
      email: "mohammed@albir.org.sa",
      password: hashPassword("mgr123"),
      role: "مدير",
      branchId: "BR-002",
      status: "نشط",
      created_at: ts,
    },
    {
      id: "USR-004",
      name: "نورة القحطاني",
      email: "noura@albir.org.sa",
      password: hashPassword("don123"),
      role: "موظف تبرعات",
      branchId: "BR-001",
      status: "نشط",
      created_at: ts,
    },
    {
      id: "USR-005",
      name: "فهد العتيبي",
      email: "fahad@albir.org.sa",
      password: hashPassword("proj123"),
      role: "منسق مشاريع",
      branchId: "BR-003",
      status: "نشط",
      created_at: ts,
    },
  ];
  for (const u of usersData) db.insert(users).values(u).run();

  // ============ ACCOUNTS (Chart of Accounts) ============
  const accountsData = [
    {
      id: "ACC-CASH",
      code: "1101",
      name: "الصندوق",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: 125000,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "ACC-BANK",
      code: "1102",
      name: "البنك الإسلامي",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: 2450000,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "ACC-DEPOSITS",
      code: "1103",
      name: "ودائع استثمارية",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: 500000,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "ACC-DONATIONS",
      code: "4101",
      name: "إيرادات التبرعات",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: 0,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "ACC-CHARITY",
      code: "5101",
      name: "مساعدات مالية",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: 0,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "ACC-PROJECTS",
      code: "5102",
      name: "مشاريع خيرية",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: 0,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "ACC-SALARIES",
      code: "5201",
      name: "رواتب ومكافآت",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: 0,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "ACC-ASSETS",
      code: "1501",
      name: "أصول ثابتة",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: 850000,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "ACC-DEPR",
      code: "1502",
      name: "مجمع الإهلاك",
      type: "تفصيلي",
      parent_id: null,
      currency: "SAR",
      balance: -120000,
      status: "نشط",
      created_at: ts,
    },
  ];
  for (const a of accountsData) db.insert(accounts).values(a).run();

  // ============ DONORS ============
  const donorsData = [
    {
      id: "D-001",
      name: "مؤسسة الراجحي الإنسانية",
      type: "مؤسسة",
      email: "info@rajihi.org",
      phone: "0114561234",
      city: "الرياض",
      tag: "ذهبي",
      totalDonations: 1200000,
      donationCount: 4,
      recurring: true,
      status: "نشط",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "D-002",
      name: "شركة أرامكو السعودية",
      type: "شركة",
      email: "csr@aramco.com",
      phone: "0134567890",
      city: "الدمام",
      tag: "ذهبي",
      totalDonations: 850000,
      donationCount: 2,
      recurring: false,
      status: "نشط",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "D-003",
      name: "عبدالله بن سليمان العتيبي",
      type: "فرد",
      email: "abdullah@gmail.com",
      phone: "0551234567",
      city: "الرياض",
      tag: "فضي",
      totalDonations: 420000,
      donationCount: 12,
      recurring: true,
      status: "نشط",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "D-004",
      name: "مؤسسة محمد وفهد العتيبي",
      type: "مؤسسة",
      email: "info@alotaibi.org",
      phone: "0119876543",
      city: "جدة",
      tag: "ذهبي",
      totalDonations: 680000,
      donationCount: 5,
      recurring: true,
      status: "نشط",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "D-005",
      name: "نورة بنت محمد القحطاني",
      type: "فرد",
      email: "noura.q@email.com",
      phone: "0559876543",
      city: "الرياض",
      tag: "برونزي",
      totalDonations: 220000,
      donationCount: 8,
      recurring: false,
      status: "نشط",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "D-006",
      name: "شركة الاتصالات السعودية",
      type: "شركة",
      email: "csr@stc.com.sa",
      phone: "0115000000",
      city: "الرياض",
      tag: "فضي",
      totalDonations: 180000,
      donationCount: 2,
      recurring: true,
      status: "نشط",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "D-007",
      name: "سلطان العتيبي",
      type: "فرد",
      email: "sultan@gmail.com",
      phone: "0554567890",
      city: "الدمام",
      tag: "فضي",
      totalDonations: 95000,
      donationCount: 3,
      recurring: false,
      status: "نشط",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "D-008",
      name: "شركة الزامل",
      type: "شركة",
      email: "info@zamil.com",
      phone: "0137890123",
      city: "الدمام",
      tag: "برونزي",
      totalDonations: 65000,
      donationCount: 1,
      recurring: false,
      status: "نشط",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
  ];
  for (const d of donorsData) db.insert(donors).values(d).run();

  // ============ CAMPAIGNS ============
  const campaignsData = [
    {
      id: "CMP-001",
      name: "كفالة الأيتام",
      goal: 1200000,
      raised: 1240000,
      start_date: "1446/01/01",
      end_date: "1446/12/30",
      status: "نشط",
      description: "حملة كفالة الأيتام الشهرية",
      created_by: "USR-004",
      created_at: ts,
    },
    {
      id: "CMP-002",
      name: "كسوة الشتاء",
      goal: 800000,
      raised: 620000,
      start_date: "1446/07/01",
      end_date: "1446/09/30",
      status: "نشط",
      description: "حملة كسوة الشتاء للمحتاجين",
      created_by: "USR-004",
      created_at: ts,
    },
    {
      id: "CMP-003",
      name: "إفطار صائم",
      goal: 600000,
      raised: 860000,
      start_date: "1446/01/01",
      end_date: "1446/09/30",
      status: "منتهية",
      description: "حملة إفطار صائم خلال رمضان",
      created_by: "USR-004",
      created_at: ts,
    },
    {
      id: "CMP-004",
      name: "علاج المرضى",
      goal: 1500000,
      raised: 380000,
      start_date: "1446/01/01",
      end_date: "1446/12/30",
      status: "نشط",
      description: "حملة دعم علاج المرضى",
      created_by: "USR-004",
      created_at: ts,
    },
  ];
  for (const c of campaignsData) db.insert(campaigns).values(c).run();

  // ============ PROJECTS ============
  const projectsData = [
    {
      id: "PRJ-001",
      name: "كفالة الأيتام",
      manager: "فهد العتيبي",
      budget: 1200000,
      spent: 980000,
      donations: 1240000,
      beneficiaryCount: 340,
      progress: 82,
      status: "نشط",
      startDate: "1446/01/01",
      endDate: "1446/12/30",
      description: "مشروع كفالة الأيتام الشهري",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "PRJ-002",
      name: "السلال الغذائية",
      manager: "نورة القحطاني",
      budget: 600000,
      spent: 520000,
      donations: 540000,
      beneficiaryCount: 850,
      progress: 90,
      status: "نشط",
      startDate: "1446/01/01",
      endDate: "1446/06/30",
      description: "توزيع سلال غذائية شهرية",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "PRJ-003",
      name: "كسوة الشتاء",
      manager: "سلطان العتيبي",
      budget: 450000,
      spent: 380000,
      donations: 620000,
      beneficiaryCount: 420,
      progress: 84,
      status: "مكتمل",
      startDate: "1445/07/01",
      endDate: "1446/03/30",
      description: "حملة كسوة الشتاء",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "PRJ-004",
      name: "علاج المرضى",
      manager: "سارة الزهراني",
      budget: 2000000,
      spent: 350000,
      donations: 380000,
      beneficiaryCount: 25,
      progress: 18,
      status: "نشط",
      startDate: "1446/01/01",
      endDate: "1446/12/30",
      description: "دعم علاج المرضى المحتاجين",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "PRJ-005",
      name: "حفر الآبار",
      manager: "فهد العتيبي",
      budget: 300000,
      spent: 0,
      donations: 0,
      beneficiaryCount: 0,
      progress: 0,
      status: "مخطط",
      startDate: "1446/07/01",
      endDate: "1447/06/30",
      description: "حفر آبار مياه نظيفة",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
  ];
  for (const p of projectsData) db.insert(projects).values(p).run();

  // ============ DONATIONS ============
  const donationsData = [
    {
      id: "DN-001",
      donorId: "D-001",
      projectId: "PRJ-001",
      campaignId: "CMP-001",
      amount: 500000,
      method: "تحويل بنكي",
      channel: "مصرف الراجحي",
      status: "مؤكد",
      receiptId: "RCP-001",
      date: "1446/10/01",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "DN-002",
      donorId: "D-002",
      projectId: "PRJ-004",
      campaignId: "CMP-004",
      amount: 300000,
      method: "شيك",
      channel: " HSBC",
      status: "مؤكد",
      receiptId: "RCP-002",
      date: "1446/10/03",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "DN-003",
      donorId: "D-003",
      projectId: "PRJ-001",
      campaignId: "CMP-001",
      amount: 10000,
      method: "نقدي",
      channel: "مباشر",
      status: "مؤكد",
      receiptId: "RCP-003",
      date: "1446/10/05",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "DN-004",
      donorId: "D-004",
      projectId: "PRJ-002",
      campaignId: "CMP-002",
      amount: 200000,
      method: "تحويل بنكي",
      channel: "مصرف الإنماء",
      status: "مؤكد",
      receiptId: "RCP-004",
      date: "1446/10/08",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "DN-005",
      donorId: "D-005",
      projectId: null,
      campaignId: null,
      amount: 5000,
      method: "نقدي",
      channel: "مباشر",
      status: "مسودة",
      receiptId: null,
      date: "1446/10/10",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "DN-006",
      donorId: "D-006",
      projectId: "PRJ-003",
      campaignId: "CMP-002",
      amount: 80000,
      method: "تحويل بنكي",
      channel: "مصرف الراجحي",
      status: "مؤكد",
      receiptId: "RCP-005",
      date: "1446/10/11",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "DN-007",
      donorId: "D-001",
      projectId: "PRJ-004",
      campaignId: "CMP-004",
      amount: 700000,
      method: "تحويل بنكي",
      channel: "مصرف الراجحي",
      status: "مؤكد",
      receiptId: "RCP-006",
      date: "1446/10/12",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "DN-008",
      donorId: "D-007",
      projectId: "PRJ-002",
      campaignId: null,
      amount: 3000,
      method: "نقدي",
      channel: "مباشر",
      status: "مؤكد",
      receiptId: "RCP-007",
      date: "1446/10/12",
      created_by: "USR-004",
      created_at: ts,
      updated_at: ts,
    },
  ];
  for (const d of donationsData) db.insert(donations).values(d).run();

  // ============ BENEFICIARIES ============
  const beneficiariesData = [
    {
      id: "BEN-001",
      name: "أسرة أحمد العمري",
      idNumber: "1012345678",
      phone: "0551112233",
      city: "الرياض",
      category: "أسر محتاجة",
      status: "فعال",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "BEN-002",
      name: "فاطمة السلمي",
      idNumber: "1023456789",
      phone: "0552223344",
      city: "جدة",
      category: "أرملة",
      status: "فعال",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "BEN-003",
      name: "أسرة سعيد الغامدي",
      idNumber: "1034567890",
      phone: "0553334455",
      city: "الدمام",
      category: "أيتام",
      status: "فعال",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "BEN-004",
      name: "محمد العتيبي",
      idNumber: "1045678901",
      phone: "0554445566",
      city: "الرياض",
      category: "مريض",
      status: "فعال",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "BEN-005",
      name: "خالد القرني",
      idNumber: "1056789012",
      phone: "0555556677",
      city: "مكة",
      category: "عاطل",
      status: "فعال",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
    {
      id: "BEN-006",
      name: "نورة القحطاني",
      idNumber: "1067890123",
      phone: "0556667788",
      city: "الرياض",
      category: "أرملة",
      status: "فعال",
      created_by: "USR-005",
      created_at: ts,
      updated_at: ts,
    },
  ];
  for (const b of beneficiariesData) db.insert(beneficiaries).values(b).run();

  // ============ AID RECORDS ============
  const aidData = [
    {
      id: "AID-001",
      beneficiaryId: "BEN-001",
      projectId: "PRJ-002",
      type: "سلة غذائية",
      amount: 350,
      status: "مصروف",
      date: "1446/10/05",
      approvedBy: "USR-005",
      approvedAt: ts,
      created_by: "USR-005",
      created_at: ts,
    },
    {
      id: "AID-002",
      beneficiaryId: "BEN-003",
      projectId: "PRJ-001",
      type: "مساعدة شهرية",
      amount: 1500,
      status: "مصروف",
      date: "1446/10/01",
      approvedBy: "USR-005",
      approvedAt: ts,
      created_by: "USR-005",
      created_at: ts,
    },
    {
      id: "AID-003",
      beneficiaryId: "BEN-004",
      projectId: "PRJ-004",
      type: "علاج",
      amount: 12000,
      status: "مصروف",
      date: "1446/09/15",
      approvedBy: "USR-005",
      approvedAt: ts,
      created_by: "USR-005",
      created_at: ts,
    },
    {
      id: "AID-004",
      beneficiaryId: "BEN-002",
      projectId: null,
      type: "مساعدة عاجلة",
      amount: 5000,
      status: "بانتظار الموافقة",
      date: "1446/10/11",
      created_by: "USR-005",
      created_at: ts,
    },
    {
      id: "AID-005",
      beneficiaryId: "BEN-005",
      projectId: "PRJ-002",
      type: "كسوة شتاء",
      amount: 800,
      status: "مصروف",
      date: "1446/09/20",
      approvedBy: "USR-005",
      approvedAt: ts,
      created_by: "USR-005",
      created_at: ts,
    },
  ];
  for (const a of aidData) db.insert(aidRecords).values(a).run();

  // ============ SUPPLIERS ============
  const suppliersData = [
    {
      id: "SUP-001",
      name: "شركة تموين السعودية",
      activity: "تموين غذائي",
      phone: "0112345678",
      email: "info@supply.sa",
      taxNumber: "300123456700001",
      status: "نشط",
      created_at: ts,
    },
    {
      id: "SUP-002",
      name: "مؤسسة العلا للتجهيزات",
      activity: "تجهيزات مكتبية",
      phone: "0123456789",
      email: "info@alaa.sa",
      taxNumber: "300123456700002",
      status: "نشط",
      created_at: ts,
    },
    {
      id: "SUP-003",
      name: "شركة الإمداد الذهبي",
      activity: "معدات وإنظمة",
      phone: "0134567890",
      email: "info@goldsupply.sa",
      taxNumber: "300123456700003",
      status: "نشط",
      created_at: ts,
    },
  ];
  for (const s of suppliersData) db.insert(suppliers).values(s).run();

  // ============ WAREHOUSES ============
  const warehousesData = [
    {
      id: "WH-001",
      name: "المستودع الرئيسي - الرياض",
      location: "حي المروة، الرياض",
      manager: "عبدالله السبيعي",
      capacity: 500,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "WH-002",
      name: "مستودع جدة",
      location: "حي الصفا، جدة",
      manager: "أحمد الزهراني",
      capacity: 300,
      status: "نشط",
      created_at: ts,
    },
  ];
  for (const w of warehousesData) db.insert(warehouses).values(w).run();

  // ============ INVENTORY ============
  const inventoryData = [
    {
      id: "INV-001",
      name: "سلة غذائية",
      sku: "FOOD-001",
      unit: "قطعة",
      category: "مساعدات",
      warehouseId: "WH-001",
      quantity: 450,
      minQuantity: 50,
      price: 350,
      status: "متوفر",
      created_at: ts,
    },
    {
      id: "INV-002",
      name: "بطانية شتوية",
      sku: "BLANKET-001",
      unit: "قطعة",
      category: "ملابس",
      warehouseId: "WH-001",
      quantity: 280,
      minQuantity: 30,
      price: 180,
      status: "متوفر",
      created_at: ts,
    },
    {
      id: "INV-003",
      name: "تمرة غذائية",
      sku: "DATE-001",
      unit: "كيس",
      category: "مساعدات",
      warehouseId: "WH-002",
      quantity: 15,
      minQuantity: 20,
      price: 45,
      status: "منخفض",
      created_at: ts,
    },
  ];
  for (const i of inventoryData) db.insert(inventoryItems).values(i).run();

  // ============ COST CENTERS ============
  const ccData = [
    {
      id: "CC-001",
      code: "CC001",
      name: "إدارة المساجد",
      manager: "سلطان العتيبي",
      budget: 200000,
      spent: 85000,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "CC-002",
      code: "CC002",
      name: "إدارة التبرعات",
      manager: "نورة القحطاني",
      budget: 50000,
      spent: 22000,
      status: "نشط",
      created_at: ts,
    },
    {
      id: "CC-003",
      code: "CC003",
      name: "الإدارة المالية",
      manager: "سارة الزهراني",
      budget: 150000,
      spent: 95000,
      status: "نشط",
      created_at: ts,
    },
  ];
  for (const c of ccData) db.insert(costCenters).values(c).run();

  // ============ APPROVALS ============
  const approvalsData = [
    {
      id: "APR-001",
      type: "مساعدة",
      subject: "مساعدة طارئة - أسرة العمري",
      requester: "فهد العتيبي",
      amount: 8500,
      status: "بانتظار موافقتي",
      priority: "عالية",
      level: 2,
      projectId: "PRJ-002",
      notes: "حالة اجتماعية صعبة",
      created_at: ts,
    },
    {
      id: "APR-002",
      type: "قيد يومية",
      subject: "ترحيل قيد تبرع 500,000 ر.س",
      requester: "سارة الزهراني",
      amount: 500000,
      status: "معتمد",
      priority: "متوسطة",
      level: 1,
      notes: "تبرع من مؤسسة الراجحي",
      created_at: ts,
    },
    {
      id: "APR-003",
      type: "طلب شراء",
      subject: "طلب شراء مستلزمات طبية",
      requester: "نورة القحطاني",
      amount: 45000,
      status: "بانتظار موافقتي",
      priority: "متوسطة",
      level: 1,
      notes: "للمشروع الصحي",
      created_at: ts,
    },
  ];
  for (const a of approvalsData) db.insert(approvals).values(a).run();

  // Initial audit log
  addAudit(
    "نظام",
    "التهيئة",
    "INIT",
    "تم تهيئة قاعدة البيانات التجريبية",
    "USR-001",
    "سعد الغامدي",
  );
}

// Auto-seed — wrapped so module import does not hang on DB failure
try {
  seedDemoData();
} catch (e) {
  console.error("[seed] auto-seed skipped:", e instanceof Error ? e.message : e);
}
