/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HrRouteImport } from './routes/hr'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as EndowmentsRouteImport } from './routes/endowments'
import { Route as EndowmentReturnsRouteImport } from './routes/endowment-returns'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as DonorOrgsRouteImport } from './routes/donor-orgs'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AidRouteImport } from './routes/aid'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsOrgRouteImport } from './routes/settings.org'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsBranchesRouteImport } from './routes/settings.branches'
import { Route as SettingsBackupRouteImport } from './routes/settings.backup'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProcurementSuppliersRouteImport } from './routes/procurement.suppliers'
import { Route as ProcurementRequestsRouteImport } from './routes/procurement.requests'
import { Route as ProcurementQuotesRouteImport } from './routes/procurement.quotes'
import { Route as ProcurementOrdersRouteImport } from './routes/procurement.orders'
import { Route as InventoryWarehousesRouteImport } from './routes/inventory.warehouses'
import { Route as InventoryStocktakeRouteImport } from './routes/inventory.stocktake'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as FinanceStatementsRouteImport } from './routes/finance.statements'
import { Route as FinanceLedgerRouteImport } from './routes/finance.ledger'
import { Route as FinanceJournalRouteImport } from './routes/finance.journal'
import { Route as FinanceCostCentersRouteImport } from './routes/finance.cost-centers'
import { Route as FinanceClosingRouteImport } from './routes/finance.closing'
import { Route as FinanceBudgetsRouteImport } from './routes/finance.budgets'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'
import { Route as DonorsNewRouteImport } from './routes/donors.new'
import { Route as DonorsIdRouteImport } from './routes/donors.$id'
import { Route as DonationsNewRouteImport } from './routes/donations.new'
import { Route as BeneficiariesNewRouteImport } from './routes/beneficiaries.new'
import { Route as BeneficiariesIdRouteImport } from './routes/beneficiaries.$id'
import { Route as AidNewRouteImport } from './routes/aid.new'
import { Route as ProjectsIdEditRouteImport } from './routes/projects.$id.edit'
import { Route as FinanceJournalNewRouteImport } from './routes/finance.journal.new'
import { Route as FinanceBudgetsNewRouteImport } from './routes/finance.budgets.new'
import { Route as FinanceAccountsNewRouteImport } from './routes/finance.accounts.new'
import { Route as DonorsIdEditRouteImport } from './routes/donors.$id.edit'
import { Route as DonationsIdEditRouteImport } from './routes/donations.$id.edit'
import { Route as BeneficiariesIdEditRouteImport } from './routes/beneficiaries.$id.edit'
import { Route as AidIdEditRouteImport } from './routes/aid.$id.edit'
import { Route as FinanceJournalIdEditRouteImport } from './routes/finance.journal.$id.edit'
import { Route as FinanceBudgetsIdEditRouteImport } from './routes/finance.budgets.$id.edit'
import { Route as FinanceAccountsIdEditRouteImport } from './routes/finance.accounts.$id.edit'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const EndowmentsRoute = EndowmentsRouteImport.update({
  id: '/endowments',
  path: '/endowments',
  getParentRoute: () => rootRouteImport,
} as any)
const EndowmentReturnsRoute = EndowmentReturnsRouteImport.update({
  id: '/endowment-returns',
  path: '/endowment-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorOrgsRoute = DonorOrgsRouteImport.update({
  id: '/donor-orgs',
  path: '/donor-orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AidRoute = AidRouteImport.update({
  id: '/aid',
  path: '/aid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrgRoute = SettingsOrgRouteImport.update({
  id: '/settings/org',
  path: '/settings/org',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBranchesRoute = SettingsBranchesRouteImport.update({
  id: '/settings/branches',
  path: '/settings/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/settings/backup',
  path: '/settings/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProcurementSuppliersRoute = ProcurementSuppliersRouteImport.update({
  id: '/procurement/suppliers',
  path: '/procurement/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRequestsRoute = ProcurementRequestsRouteImport.update({
  id: '/procurement/requests',
  path: '/procurement/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementQuotesRoute = ProcurementQuotesRouteImport.update({
  id: '/procurement/quotes',
  path: '/procurement/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementOrdersRoute = ProcurementOrdersRouteImport.update({
  id: '/procurement/orders',
  path: '/procurement/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWarehousesRoute = InventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStocktakeRoute = InventoryStocktakeRouteImport.update({
  id: '/inventory/stocktake',
  path: '/inventory/stocktake',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory/items',
  path: '/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceStatementsRoute = FinanceStatementsRouteImport.update({
  id: '/finance/statements',
  path: '/finance/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceLedgerRoute = FinanceLedgerRouteImport.update({
  id: '/finance/ledger',
  path: '/finance/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceJournalRoute = FinanceJournalRouteImport.update({
  id: '/finance/journal',
  path: '/finance/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCostCentersRoute = FinanceCostCentersRouteImport.update({
  id: '/finance/cost-centers',
  path: '/finance/cost-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceClosingRoute = FinanceClosingRouteImport.update({
  id: '/finance/closing',
  path: '/finance/closing',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/finance/budgets',
  path: '/finance/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/finance/accounts',
  path: '/finance/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsNewRoute = DonorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DonorsRoute,
} as any)
const DonorsIdRoute = DonorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DonorsRoute,
} as any)
const DonationsNewRoute = DonationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DonationsRoute,
} as any)
const BeneficiariesNewRoute = BeneficiariesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BeneficiariesRoute,
} as any)
const BeneficiariesIdRoute = BeneficiariesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BeneficiariesRoute,
} as any)
const AidNewRoute = AidNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AidRoute,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const FinanceJournalNewRoute = FinanceJournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FinanceJournalRoute,
} as any)
const FinanceBudgetsNewRoute = FinanceBudgetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FinanceBudgetsRoute,
} as any)
const FinanceAccountsNewRoute = FinanceAccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FinanceAccountsRoute,
} as any)
const DonorsIdEditRoute = DonorsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DonorsIdRoute,
} as any)
const DonationsIdEditRoute = DonationsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => DonationsRoute,
} as any)
const BeneficiariesIdEditRoute = BeneficiariesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BeneficiariesIdRoute,
} as any)
const AidIdEditRoute = AidIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AidRoute,
} as any)
const FinanceJournalIdEditRoute = FinanceJournalIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => FinanceJournalRoute,
} as any)
const FinanceBudgetsIdEditRoute = FinanceBudgetsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => FinanceBudgetsRoute,
} as any)
const FinanceAccountsIdEditRoute = FinanceAccountsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => FinanceAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aid': typeof AidRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRouteWithChildren
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/aid/new': typeof AidNewRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRouteWithChildren
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/donations/new': typeof DonationsNewRoute
  '/donors/$id': typeof DonorsIdRouteWithChildren
  '/donors/new': typeof DonorsNewRoute
  '/finance/accounts': typeof FinanceAccountsRouteWithChildren
  '/finance/budgets': typeof FinanceBudgetsRouteWithChildren
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRouteWithChildren
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/stocktake': typeof InventoryStocktakeRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/quotes': typeof ProcurementQuotesRoute
  '/procurement/requests': typeof ProcurementRequestsRoute
  '/procurement/suppliers': typeof ProcurementSuppliersRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/aid/$id/edit': typeof AidIdEditRoute
  '/beneficiaries/$id/edit': typeof BeneficiariesIdEditRoute
  '/donations/$id/edit': typeof DonationsIdEditRoute
  '/donors/$id/edit': typeof DonorsIdEditRoute
  '/finance/accounts/new': typeof FinanceAccountsNewRoute
  '/finance/budgets/new': typeof FinanceBudgetsNewRoute
  '/finance/journal/new': typeof FinanceJournalNewRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/finance/accounts/$id/edit': typeof FinanceAccountsIdEditRoute
  '/finance/budgets/$id/edit': typeof FinanceBudgetsIdEditRoute
  '/finance/journal/$id/edit': typeof FinanceJournalIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aid': typeof AidRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRouteWithChildren
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/aid/new': typeof AidNewRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRouteWithChildren
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/donations/new': typeof DonationsNewRoute
  '/donors/$id': typeof DonorsIdRouteWithChildren
  '/donors/new': typeof DonorsNewRoute
  '/finance/accounts': typeof FinanceAccountsRouteWithChildren
  '/finance/budgets': typeof FinanceBudgetsRouteWithChildren
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRouteWithChildren
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/stocktake': typeof InventoryStocktakeRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/quotes': typeof ProcurementQuotesRoute
  '/procurement/requests': typeof ProcurementRequestsRoute
  '/procurement/suppliers': typeof ProcurementSuppliersRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/aid/$id/edit': typeof AidIdEditRoute
  '/beneficiaries/$id/edit': typeof BeneficiariesIdEditRoute
  '/donations/$id/edit': typeof DonationsIdEditRoute
  '/donors/$id/edit': typeof DonorsIdEditRoute
  '/finance/accounts/new': typeof FinanceAccountsNewRoute
  '/finance/budgets/new': typeof FinanceBudgetsNewRoute
  '/finance/journal/new': typeof FinanceJournalNewRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/finance/accounts/$id/edit': typeof FinanceAccountsIdEditRoute
  '/finance/budgets/$id/edit': typeof FinanceBudgetsIdEditRoute
  '/finance/journal/$id/edit': typeof FinanceJournalIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aid': typeof AidRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRouteWithChildren
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/aid/new': typeof AidNewRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRouteWithChildren
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/donations/new': typeof DonationsNewRoute
  '/donors/$id': typeof DonorsIdRouteWithChildren
  '/donors/new': typeof DonorsNewRoute
  '/finance/accounts': typeof FinanceAccountsRouteWithChildren
  '/finance/budgets': typeof FinanceBudgetsRouteWithChildren
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRouteWithChildren
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/stocktake': typeof InventoryStocktakeRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/quotes': typeof ProcurementQuotesRoute
  '/procurement/requests': typeof ProcurementRequestsRoute
  '/procurement/suppliers': typeof ProcurementSuppliersRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/aid/$id/edit': typeof AidIdEditRoute
  '/beneficiaries/$id/edit': typeof BeneficiariesIdEditRoute
  '/donations/$id/edit': typeof DonationsIdEditRoute
  '/donors/$id/edit': typeof DonorsIdEditRoute
  '/finance/accounts/new': typeof FinanceAccountsNewRoute
  '/finance/budgets/new': typeof FinanceBudgetsNewRoute
  '/finance/journal/new': typeof FinanceJournalNewRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/finance/accounts/$id/edit': typeof FinanceAccountsIdEditRoute
  '/finance/budgets/$id/edit': typeof FinanceBudgetsIdEditRoute
  '/finance/journal/$id/edit': typeof FinanceJournalIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/login'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/aid/new'
    | '/beneficiaries/$id'
    | '/beneficiaries/new'
    | '/donations/new'
    | '/donors/$id'
    | '/donors/new'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
    | '/aid/$id/edit'
    | '/beneficiaries/$id/edit'
    | '/donations/$id/edit'
    | '/donors/$id/edit'
    | '/finance/accounts/new'
    | '/finance/budgets/new'
    | '/finance/journal/new'
    | '/projects/$id/edit'
    | '/finance/accounts/$id/edit'
    | '/finance/budgets/$id/edit'
    | '/finance/journal/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/login'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/aid/new'
    | '/beneficiaries/$id'
    | '/beneficiaries/new'
    | '/donations/new'
    | '/donors/$id'
    | '/donors/new'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
    | '/aid/$id/edit'
    | '/beneficiaries/$id/edit'
    | '/donations/$id/edit'
    | '/donors/$id/edit'
    | '/finance/accounts/new'
    | '/finance/budgets/new'
    | '/finance/journal/new'
    | '/projects/$id/edit'
    | '/finance/accounts/$id/edit'
    | '/finance/budgets/$id/edit'
    | '/finance/journal/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/login'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/aid/new'
    | '/beneficiaries/$id'
    | '/beneficiaries/new'
    | '/donations/new'
    | '/donors/$id'
    | '/donors/new'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
    | '/aid/$id/edit'
    | '/beneficiaries/$id/edit'
    | '/donations/$id/edit'
    | '/donors/$id/edit'
    | '/finance/accounts/new'
    | '/finance/budgets/new'
    | '/finance/journal/new'
    | '/projects/$id/edit'
    | '/finance/accounts/$id/edit'
    | '/finance/budgets/$id/edit'
    | '/finance/journal/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AidRoute: typeof AidRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  AssetsRoute: typeof AssetsRoute
  AuditRoute: typeof AuditRoute
  BeneficiariesRoute: typeof BeneficiariesRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  DistributionRoute: typeof DistributionRoute
  DonationsRoute: typeof DonationsRouteWithChildren
  DonorOrgsRoute: typeof DonorOrgsRoute
  DonorsRoute: typeof DonorsRouteWithChildren
  EndowmentReturnsRoute: typeof EndowmentReturnsRoute
  EndowmentsRoute: typeof EndowmentsRoute
  GrantsRoute: typeof GrantsRoute
  HrRoute: typeof HrRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  MembershipsRoute: typeof MembershipsRoute
  NotificationsRoute: typeof NotificationsRoute
  PermissionsRoute: typeof PermissionsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReceiptsRoute: typeof ReceiptsRoute
  RecurringRoute: typeof RecurringRoute
  ReportsRoute: typeof ReportsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  FinanceAccountsRoute: typeof FinanceAccountsRouteWithChildren
  FinanceBudgetsRoute: typeof FinanceBudgetsRouteWithChildren
  FinanceClosingRoute: typeof FinanceClosingRoute
  FinanceCostCentersRoute: typeof FinanceCostCentersRoute
  FinanceJournalRoute: typeof FinanceJournalRouteWithChildren
  FinanceLedgerRoute: typeof FinanceLedgerRoute
  FinanceStatementsRoute: typeof FinanceStatementsRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  InventoryStocktakeRoute: typeof InventoryStocktakeRoute
  InventoryWarehousesRoute: typeof InventoryWarehousesRoute
  ProcurementOrdersRoute: typeof ProcurementOrdersRoute
  ProcurementQuotesRoute: typeof ProcurementQuotesRoute
  ProcurementRequestsRoute: typeof ProcurementRequestsRoute
  ProcurementSuppliersRoute: typeof ProcurementSuppliersRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsBranchesRoute: typeof SettingsBranchesRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsOrgRoute: typeof SettingsOrgRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endowments': {
      id: '/endowments'
      path: '/endowments'
      fullPath: '/endowments'
      preLoaderRoute: typeof EndowmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endowment-returns': {
      id: '/endowment-returns'
      path: '/endowment-returns'
      fullPath: '/endowment-returns'
      preLoaderRoute: typeof EndowmentReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-orgs': {
      id: '/donor-orgs'
      path: '/donor-orgs'
      fullPath: '/donor-orgs'
      preLoaderRoute: typeof DonorOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aid': {
      id: '/aid'
      path: '/aid'
      fullPath: '/aid'
      preLoaderRoute: typeof AidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/org': {
      id: '/settings/org'
      path: '/settings/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof SettingsOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/branches': {
      id: '/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof SettingsBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/procurement/suppliers': {
      id: '/procurement/suppliers'
      path: '/procurement/suppliers'
      fullPath: '/procurement/suppliers'
      preLoaderRoute: typeof ProcurementSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/requests': {
      id: '/procurement/requests'
      path: '/procurement/requests'
      fullPath: '/procurement/requests'
      preLoaderRoute: typeof ProcurementRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/quotes': {
      id: '/procurement/quotes'
      path: '/procurement/quotes'
      fullPath: '/procurement/quotes'
      preLoaderRoute: typeof ProcurementQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/orders': {
      id: '/procurement/orders'
      path: '/procurement/orders'
      fullPath: '/procurement/orders'
      preLoaderRoute: typeof ProcurementOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/warehouses': {
      id: '/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof InventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stocktake': {
      id: '/inventory/stocktake'
      path: '/inventory/stocktake'
      fullPath: '/inventory/stocktake'
      preLoaderRoute: typeof InventoryStocktakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/statements': {
      id: '/finance/statements'
      path: '/finance/statements'
      fullPath: '/finance/statements'
      preLoaderRoute: typeof FinanceStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/ledger': {
      id: '/finance/ledger'
      path: '/finance/ledger'
      fullPath: '/finance/ledger'
      preLoaderRoute: typeof FinanceLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/journal': {
      id: '/finance/journal'
      path: '/finance/journal'
      fullPath: '/finance/journal'
      preLoaderRoute: typeof FinanceJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/cost-centers': {
      id: '/finance/cost-centers'
      path: '/finance/cost-centers'
      fullPath: '/finance/cost-centers'
      preLoaderRoute: typeof FinanceCostCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/closing': {
      id: '/finance/closing'
      path: '/finance/closing'
      fullPath: '/finance/closing'
      preLoaderRoute: typeof FinanceClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/finance/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/finance/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors/new': {
      id: '/donors/new'
      path: '/new'
      fullPath: '/donors/new'
      preLoaderRoute: typeof DonorsNewRouteImport
      parentRoute: typeof DonorsRoute
    }
    '/donors/$id': {
      id: '/donors/$id'
      path: '/$id'
      fullPath: '/donors/$id'
      preLoaderRoute: typeof DonorsIdRouteImport
      parentRoute: typeof DonorsRoute
    }
    '/donations/new': {
      id: '/donations/new'
      path: '/new'
      fullPath: '/donations/new'
      preLoaderRoute: typeof DonationsNewRouteImport
      parentRoute: typeof DonationsRoute
    }
    '/beneficiaries/new': {
      id: '/beneficiaries/new'
      path: '/new'
      fullPath: '/beneficiaries/new'
      preLoaderRoute: typeof BeneficiariesNewRouteImport
      parentRoute: typeof BeneficiariesRoute
    }
    '/beneficiaries/$id': {
      id: '/beneficiaries/$id'
      path: '/$id'
      fullPath: '/beneficiaries/$id'
      preLoaderRoute: typeof BeneficiariesIdRouteImport
      parentRoute: typeof BeneficiariesRoute
    }
    '/aid/new': {
      id: '/aid/new'
      path: '/new'
      fullPath: '/aid/new'
      preLoaderRoute: typeof AidNewRouteImport
      parentRoute: typeof AidRoute
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/finance/journal/new': {
      id: '/finance/journal/new'
      path: '/new'
      fullPath: '/finance/journal/new'
      preLoaderRoute: typeof FinanceJournalNewRouteImport
      parentRoute: typeof FinanceJournalRoute
    }
    '/finance/budgets/new': {
      id: '/finance/budgets/new'
      path: '/new'
      fullPath: '/finance/budgets/new'
      preLoaderRoute: typeof FinanceBudgetsNewRouteImport
      parentRoute: typeof FinanceBudgetsRoute
    }
    '/finance/accounts/new': {
      id: '/finance/accounts/new'
      path: '/new'
      fullPath: '/finance/accounts/new'
      preLoaderRoute: typeof FinanceAccountsNewRouteImport
      parentRoute: typeof FinanceAccountsRoute
    }
    '/donors/$id/edit': {
      id: '/donors/$id/edit'
      path: '/edit'
      fullPath: '/donors/$id/edit'
      preLoaderRoute: typeof DonorsIdEditRouteImport
      parentRoute: typeof DonorsIdRoute
    }
    '/donations/$id/edit': {
      id: '/donations/$id/edit'
      path: '/$id/edit'
      fullPath: '/donations/$id/edit'
      preLoaderRoute: typeof DonationsIdEditRouteImport
      parentRoute: typeof DonationsRoute
    }
    '/beneficiaries/$id/edit': {
      id: '/beneficiaries/$id/edit'
      path: '/edit'
      fullPath: '/beneficiaries/$id/edit'
      preLoaderRoute: typeof BeneficiariesIdEditRouteImport
      parentRoute: typeof BeneficiariesIdRoute
    }
    '/aid/$id/edit': {
      id: '/aid/$id/edit'
      path: '/$id/edit'
      fullPath: '/aid/$id/edit'
      preLoaderRoute: typeof AidIdEditRouteImport
      parentRoute: typeof AidRoute
    }
    '/finance/journal/$id/edit': {
      id: '/finance/journal/$id/edit'
      path: '/$id/edit'
      fullPath: '/finance/journal/$id/edit'
      preLoaderRoute: typeof FinanceJournalIdEditRouteImport
      parentRoute: typeof FinanceJournalRoute
    }
    '/finance/budgets/$id/edit': {
      id: '/finance/budgets/$id/edit'
      path: '/$id/edit'
      fullPath: '/finance/budgets/$id/edit'
      preLoaderRoute: typeof FinanceBudgetsIdEditRouteImport
      parentRoute: typeof FinanceBudgetsRoute
    }
    '/finance/accounts/$id/edit': {
      id: '/finance/accounts/$id/edit'
      path: '/$id/edit'
      fullPath: '/finance/accounts/$id/edit'
      preLoaderRoute: typeof FinanceAccountsIdEditRouteImport
      parentRoute: typeof FinanceAccountsRoute
    }
  }
}

interface AidRouteChildren {
  AidNewRoute: typeof AidNewRoute
  AidIdEditRoute: typeof AidIdEditRoute
}

const AidRouteChildren: AidRouteChildren = {
  AidNewRoute: AidNewRoute,
  AidIdEditRoute: AidIdEditRoute,
}

const AidRouteWithChildren = AidRoute._addFileChildren(AidRouteChildren)

interface BeneficiariesIdRouteChildren {
  BeneficiariesIdEditRoute: typeof BeneficiariesIdEditRoute
}

const BeneficiariesIdRouteChildren: BeneficiariesIdRouteChildren = {
  BeneficiariesIdEditRoute: BeneficiariesIdEditRoute,
}

const BeneficiariesIdRouteWithChildren = BeneficiariesIdRoute._addFileChildren(
  BeneficiariesIdRouteChildren,
)

interface BeneficiariesRouteChildren {
  BeneficiariesIdRoute: typeof BeneficiariesIdRouteWithChildren
  BeneficiariesNewRoute: typeof BeneficiariesNewRoute
}

const BeneficiariesRouteChildren: BeneficiariesRouteChildren = {
  BeneficiariesIdRoute: BeneficiariesIdRouteWithChildren,
  BeneficiariesNewRoute: BeneficiariesNewRoute,
}

const BeneficiariesRouteWithChildren = BeneficiariesRoute._addFileChildren(
  BeneficiariesRouteChildren,
)

interface DonationsRouteChildren {
  DonationsNewRoute: typeof DonationsNewRoute
  DonationsIdEditRoute: typeof DonationsIdEditRoute
}

const DonationsRouteChildren: DonationsRouteChildren = {
  DonationsNewRoute: DonationsNewRoute,
  DonationsIdEditRoute: DonationsIdEditRoute,
}

const DonationsRouteWithChildren = DonationsRoute._addFileChildren(
  DonationsRouteChildren,
)

interface DonorsIdRouteChildren {
  DonorsIdEditRoute: typeof DonorsIdEditRoute
}

const DonorsIdRouteChildren: DonorsIdRouteChildren = {
  DonorsIdEditRoute: DonorsIdEditRoute,
}

const DonorsIdRouteWithChildren = DonorsIdRoute._addFileChildren(
  DonorsIdRouteChildren,
)

interface DonorsRouteChildren {
  DonorsIdRoute: typeof DonorsIdRouteWithChildren
  DonorsNewRoute: typeof DonorsNewRoute
}

const DonorsRouteChildren: DonorsRouteChildren = {
  DonorsIdRoute: DonorsIdRouteWithChildren,
  DonorsNewRoute: DonorsNewRoute,
}

const DonorsRouteWithChildren =
  DonorsRoute._addFileChildren(DonorsRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface FinanceAccountsRouteChildren {
  FinanceAccountsNewRoute: typeof FinanceAccountsNewRoute
  FinanceAccountsIdEditRoute: typeof FinanceAccountsIdEditRoute
}

const FinanceAccountsRouteChildren: FinanceAccountsRouteChildren = {
  FinanceAccountsNewRoute: FinanceAccountsNewRoute,
  FinanceAccountsIdEditRoute: FinanceAccountsIdEditRoute,
}

const FinanceAccountsRouteWithChildren = FinanceAccountsRoute._addFileChildren(
  FinanceAccountsRouteChildren,
)

interface FinanceBudgetsRouteChildren {
  FinanceBudgetsNewRoute: typeof FinanceBudgetsNewRoute
  FinanceBudgetsIdEditRoute: typeof FinanceBudgetsIdEditRoute
}

const FinanceBudgetsRouteChildren: FinanceBudgetsRouteChildren = {
  FinanceBudgetsNewRoute: FinanceBudgetsNewRoute,
  FinanceBudgetsIdEditRoute: FinanceBudgetsIdEditRoute,
}

const FinanceBudgetsRouteWithChildren = FinanceBudgetsRoute._addFileChildren(
  FinanceBudgetsRouteChildren,
)

interface FinanceJournalRouteChildren {
  FinanceJournalNewRoute: typeof FinanceJournalNewRoute
  FinanceJournalIdEditRoute: typeof FinanceJournalIdEditRoute
}

const FinanceJournalRouteChildren: FinanceJournalRouteChildren = {
  FinanceJournalNewRoute: FinanceJournalNewRoute,
  FinanceJournalIdEditRoute: FinanceJournalIdEditRoute,
}

const FinanceJournalRouteWithChildren = FinanceJournalRoute._addFileChildren(
  FinanceJournalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AidRoute: AidRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  AssetsRoute: AssetsRoute,
  AuditRoute: AuditRoute,
  BeneficiariesRoute: BeneficiariesRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  DistributionRoute: DistributionRoute,
  DonationsRoute: DonationsRouteWithChildren,
  DonorOrgsRoute: DonorOrgsRoute,
  DonorsRoute: DonorsRouteWithChildren,
  EndowmentReturnsRoute: EndowmentReturnsRoute,
  EndowmentsRoute: EndowmentsRoute,
  GrantsRoute: GrantsRoute,
  HrRoute: HrRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  MembershipsRoute: MembershipsRoute,
  NotificationsRoute: NotificationsRoute,
  PermissionsRoute: PermissionsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReceiptsRoute: ReceiptsRoute,
  RecurringRoute: RecurringRoute,
  ReportsRoute: ReportsRoute,
  WorkflowsRoute: WorkflowsRoute,
  FinanceAccountsRoute: FinanceAccountsRouteWithChildren,
  FinanceBudgetsRoute: FinanceBudgetsRouteWithChildren,
  FinanceClosingRoute: FinanceClosingRoute,
  FinanceCostCentersRoute: FinanceCostCentersRoute,
  FinanceJournalRoute: FinanceJournalRouteWithChildren,
  FinanceLedgerRoute: FinanceLedgerRoute,
  FinanceStatementsRoute: FinanceStatementsRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  InventoryStocktakeRoute: InventoryStocktakeRoute,
  InventoryWarehousesRoute: InventoryWarehousesRoute,
  ProcurementOrdersRoute: ProcurementOrdersRoute,
  ProcurementQuotesRoute: ProcurementQuotesRoute,
  ProcurementRequestsRoute: ProcurementRequestsRoute,
  ProcurementSuppliersRoute: ProcurementSuppliersRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsBranchesRoute: SettingsBranchesRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsOrgRoute: SettingsOrgRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
