/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as HrRouteImport } from './routes/hr'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as EndowmentsRouteImport } from './routes/endowments'
import { Route as EndowmentReturnsRouteImport } from './routes/endowment-returns'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as DonorOrgsRouteImport } from './routes/donor-orgs'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AidRouteImport } from './routes/aid'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsOrgRouteImport } from './routes/settings.org'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsBranchesRouteImport } from './routes/settings.branches'
import { Route as SettingsBackupRouteImport } from './routes/settings.backup'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProcurementSuppliersRouteImport } from './routes/procurement.suppliers'
import { Route as ProcurementRequestsRouteImport } from './routes/procurement.requests'
import { Route as ProcurementQuotesRouteImport } from './routes/procurement.quotes'
import { Route as ProcurementOrdersRouteImport } from './routes/procurement.orders'
import { Route as InventoryWarehousesRouteImport } from './routes/inventory.warehouses'
import { Route as InventoryStocktakeRouteImport } from './routes/inventory.stocktake'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as FinanceStatementsRouteImport } from './routes/finance.statements'
import { Route as FinanceLedgerRouteImport } from './routes/finance.ledger'
import { Route as FinanceJournalRouteImport } from './routes/finance.journal'
import { Route as FinanceCostCentersRouteImport } from './routes/finance.cost-centers'
import { Route as FinanceClosingRouteImport } from './routes/finance.closing'
import { Route as FinanceBudgetsRouteImport } from './routes/finance.budgets'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'
import { Route as DonorsIdRouteImport } from './routes/donors.$id'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const EndowmentsRoute = EndowmentsRouteImport.update({
  id: '/endowments',
  path: '/endowments',
  getParentRoute: () => rootRouteImport,
} as any)
const EndowmentReturnsRoute = EndowmentReturnsRouteImport.update({
  id: '/endowment-returns',
  path: '/endowment-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorOrgsRoute = DonorOrgsRouteImport.update({
  id: '/donor-orgs',
  path: '/donor-orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AidRoute = AidRouteImport.update({
  id: '/aid',
  path: '/aid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrgRoute = SettingsOrgRouteImport.update({
  id: '/settings/org',
  path: '/settings/org',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBranchesRoute = SettingsBranchesRouteImport.update({
  id: '/settings/branches',
  path: '/settings/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/settings/backup',
  path: '/settings/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProcurementSuppliersRoute = ProcurementSuppliersRouteImport.update({
  id: '/procurement/suppliers',
  path: '/procurement/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRequestsRoute = ProcurementRequestsRouteImport.update({
  id: '/procurement/requests',
  path: '/procurement/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementQuotesRoute = ProcurementQuotesRouteImport.update({
  id: '/procurement/quotes',
  path: '/procurement/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementOrdersRoute = ProcurementOrdersRouteImport.update({
  id: '/procurement/orders',
  path: '/procurement/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWarehousesRoute = InventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStocktakeRoute = InventoryStocktakeRouteImport.update({
  id: '/inventory/stocktake',
  path: '/inventory/stocktake',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory/items',
  path: '/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceStatementsRoute = FinanceStatementsRouteImport.update({
  id: '/finance/statements',
  path: '/finance/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceLedgerRoute = FinanceLedgerRouteImport.update({
  id: '/finance/ledger',
  path: '/finance/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceJournalRoute = FinanceJournalRouteImport.update({
  id: '/finance/journal',
  path: '/finance/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCostCentersRoute = FinanceCostCentersRouteImport.update({
  id: '/finance/cost-centers',
  path: '/finance/cost-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceClosingRoute = FinanceClosingRouteImport.update({
  id: '/finance/closing',
  path: '/finance/closing',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/finance/budgets',
  path: '/finance/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/finance/accounts',
  path: '/finance/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsIdRoute = DonorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DonorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aid': typeof AidRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRoute
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/donors/$id': typeof DonorsIdRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/stocktake': typeof InventoryStocktakeRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/quotes': typeof ProcurementQuotesRoute
  '/procurement/requests': typeof ProcurementRequestsRoute
  '/procurement/suppliers': typeof ProcurementSuppliersRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aid': typeof AidRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRoute
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/donors/$id': typeof DonorsIdRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/stocktake': typeof InventoryStocktakeRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/quotes': typeof ProcurementQuotesRoute
  '/procurement/requests': typeof ProcurementRequestsRoute
  '/procurement/suppliers': typeof ProcurementSuppliersRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aid': typeof AidRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRoute
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/donors/$id': typeof DonorsIdRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/stocktake': typeof InventoryStocktakeRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/quotes': typeof ProcurementQuotesRoute
  '/procurement/requests': typeof ProcurementRequestsRoute
  '/procurement/suppliers': typeof ProcurementSuppliersRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/donors/$id'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/donors/$id'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
  id:
    | '__root__'
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/donors/$id'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AidRoute: typeof AidRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AssetsRoute: typeof AssetsRoute
  AuditRoute: typeof AuditRoute
  BeneficiariesRoute: typeof BeneficiariesRoute
  CampaignsRoute: typeof CampaignsRoute
  DistributionRoute: typeof DistributionRoute
  DonationsRoute: typeof DonationsRoute
  DonorOrgsRoute: typeof DonorOrgsRoute
  DonorsRoute: typeof DonorsRouteWithChildren
  EndowmentReturnsRoute: typeof EndowmentReturnsRoute
  EndowmentsRoute: typeof EndowmentsRoute
  GrantsRoute: typeof GrantsRoute
  HrRoute: typeof HrRoute
  MeetingsRoute: typeof MeetingsRoute
  MembershipsRoute: typeof MembershipsRoute
  NotificationsRoute: typeof NotificationsRoute
  PermissionsRoute: typeof PermissionsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReceiptsRoute: typeof ReceiptsRoute
  RecurringRoute: typeof RecurringRoute
  ReportsRoute: typeof ReportsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceBudgetsRoute: typeof FinanceBudgetsRoute
  FinanceClosingRoute: typeof FinanceClosingRoute
  FinanceCostCentersRoute: typeof FinanceCostCentersRoute
  FinanceJournalRoute: typeof FinanceJournalRoute
  FinanceLedgerRoute: typeof FinanceLedgerRoute
  FinanceStatementsRoute: typeof FinanceStatementsRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  InventoryStocktakeRoute: typeof InventoryStocktakeRoute
  InventoryWarehousesRoute: typeof InventoryWarehousesRoute
  ProcurementOrdersRoute: typeof ProcurementOrdersRoute
  ProcurementQuotesRoute: typeof ProcurementQuotesRoute
  ProcurementRequestsRoute: typeof ProcurementRequestsRoute
  ProcurementSuppliersRoute: typeof ProcurementSuppliersRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsBranchesRoute: typeof SettingsBranchesRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsOrgRoute: typeof SettingsOrgRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endowments': {
      id: '/endowments'
      path: '/endowments'
      fullPath: '/endowments'
      preLoaderRoute: typeof EndowmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endowment-returns': {
      id: '/endowment-returns'
      path: '/endowment-returns'
      fullPath: '/endowment-returns'
      preLoaderRoute: typeof EndowmentReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-orgs': {
      id: '/donor-orgs'
      path: '/donor-orgs'
      fullPath: '/donor-orgs'
      preLoaderRoute: typeof DonorOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aid': {
      id: '/aid'
      path: '/aid'
      fullPath: '/aid'
      preLoaderRoute: typeof AidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/org': {
      id: '/settings/org'
      path: '/settings/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof SettingsOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/branches': {
      id: '/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof SettingsBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/procurement/suppliers': {
      id: '/procurement/suppliers'
      path: '/procurement/suppliers'
      fullPath: '/procurement/suppliers'
      preLoaderRoute: typeof ProcurementSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/requests': {
      id: '/procurement/requests'
      path: '/procurement/requests'
      fullPath: '/procurement/requests'
      preLoaderRoute: typeof ProcurementRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/quotes': {
      id: '/procurement/quotes'
      path: '/procurement/quotes'
      fullPath: '/procurement/quotes'
      preLoaderRoute: typeof ProcurementQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/orders': {
      id: '/procurement/orders'
      path: '/procurement/orders'
      fullPath: '/procurement/orders'
      preLoaderRoute: typeof ProcurementOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/warehouses': {
      id: '/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof InventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stocktake': {
      id: '/inventory/stocktake'
      path: '/inventory/stocktake'
      fullPath: '/inventory/stocktake'
      preLoaderRoute: typeof InventoryStocktakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/statements': {
      id: '/finance/statements'
      path: '/finance/statements'
      fullPath: '/finance/statements'
      preLoaderRoute: typeof FinanceStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/ledger': {
      id: '/finance/ledger'
      path: '/finance/ledger'
      fullPath: '/finance/ledger'
      preLoaderRoute: typeof FinanceLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/journal': {
      id: '/finance/journal'
      path: '/finance/journal'
      fullPath: '/finance/journal'
      preLoaderRoute: typeof FinanceJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/cost-centers': {
      id: '/finance/cost-centers'
      path: '/finance/cost-centers'
      fullPath: '/finance/cost-centers'
      preLoaderRoute: typeof FinanceCostCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/closing': {
      id: '/finance/closing'
      path: '/finance/closing'
      fullPath: '/finance/closing'
      preLoaderRoute: typeof FinanceClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/finance/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/finance/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors/$id': {
      id: '/donors/$id'
      path: '/$id'
      fullPath: '/donors/$id'
      preLoaderRoute: typeof DonorsIdRouteImport
      parentRoute: typeof DonorsRoute
    }
  }
}

interface DonorsRouteChildren {
  DonorsIdRoute: typeof DonorsIdRoute
}

const DonorsRouteChildren: DonorsRouteChildren = {
  DonorsIdRoute: DonorsIdRoute,
}

const DonorsRouteWithChildren =
  DonorsRoute._addFileChildren(DonorsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AidRoute: AidRoute,
  ApprovalsRoute: ApprovalsRoute,
  AssetsRoute: AssetsRoute,
  AuditRoute: AuditRoute,
  BeneficiariesRoute: BeneficiariesRoute,
  CampaignsRoute: CampaignsRoute,
  DistributionRoute: DistributionRoute,
  DonationsRoute: DonationsRoute,
  DonorOrgsRoute: DonorOrgsRoute,
  DonorsRoute: DonorsRouteWithChildren,
  EndowmentReturnsRoute: EndowmentReturnsRoute,
  EndowmentsRoute: EndowmentsRoute,
  GrantsRoute: GrantsRoute,
  HrRoute: HrRoute,
  MeetingsRoute: MeetingsRoute,
  MembershipsRoute: MembershipsRoute,
  NotificationsRoute: NotificationsRoute,
  PermissionsRoute: PermissionsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReceiptsRoute: ReceiptsRoute,
  RecurringRoute: RecurringRoute,
  ReportsRoute: ReportsRoute,
  WorkflowsRoute: WorkflowsRoute,
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceBudgetsRoute: FinanceBudgetsRoute,
  FinanceClosingRoute: FinanceClosingRoute,
  FinanceCostCentersRoute: FinanceCostCentersRoute,
  FinanceJournalRoute: FinanceJournalRoute,
  FinanceLedgerRoute: FinanceLedgerRoute,
  FinanceStatementsRoute: FinanceStatementsRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  InventoryStocktakeRoute: InventoryStocktakeRoute,
  InventoryWarehousesRoute: InventoryWarehousesRoute,
  ProcurementOrdersRoute: ProcurementOrdersRoute,
  ProcurementQuotesRoute: ProcurementQuotesRoute,
  ProcurementRequestsRoute: ProcurementRequestsRoute,
  ProcurementSuppliersRoute: ProcurementSuppliersRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsBranchesRoute: SettingsBranchesRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsOrgRoute: SettingsOrgRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
