/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HrRouteImport } from './routes/hr'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as EndowmentsRouteImport } from './routes/endowments'
import { Route as EndowmentReturnsRouteImport } from './routes/endowment-returns'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as DonorOrgsRouteImport } from './routes/donor-orgs'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AidRouteImport } from './routes/aid'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsOrgRouteImport } from './routes/settings.org'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsBranchesRouteImport } from './routes/settings.branches'
import { Route as SettingsBackupRouteImport } from './routes/settings.backup'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProcurementSuppliersRouteImport } from './routes/procurement.suppliers'
import { Route as ProcurementRequestsRouteImport } from './routes/procurement.requests'
import { Route as ProcurementQuotesRouteImport } from './routes/procurement.quotes'
import { Route as ProcurementOrdersRouteImport } from './routes/procurement.orders'
import { Route as InventoryWarehousesRouteImport } from './routes/inventory.warehouses'
import { Route as InventoryStocktakeRouteImport } from './routes/inventory.stocktake'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as FinanceStatementsRouteImport } from './routes/finance.statements'
import { Route as FinanceLedgerRouteImport } from './routes/finance.ledger'
import { Route as FinanceJournalRouteImport } from './routes/finance.journal'
import { Route as FinanceCostCentersRouteImport } from './routes/finance.cost-centers'
import { Route as FinanceClosingRouteImport } from './routes/finance.closing'
import { Route as FinanceBudgetsRouteImport } from './routes/finance.budgets'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'
import { Route as DonorsNewRouteImport } from './routes/donors.new'
import { Route as DonorsIdRouteImport } from './routes/donors.$id'
import { Route as DonationsNewRouteImport } from './routes/donations.new'
import { Route as BeneficiariesNewRouteImport } from './routes/beneficiaries.new'
import { Route as BeneficiariesIdRouteImport } from './routes/beneficiaries.$id'
import { Route as AssetsNewRouteImport } from './routes/assets.new'
import { Route as ApiReceiptsRouteImport } from './routes/api/receipts'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiDonorsRouteImport } from './routes/api/donors'
import { Route as ApiDonationsRouteImport } from './routes/api/donations'
import { Route as ApiBeneficiariesRouteImport } from './routes/api/beneficiaries'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as ApiAssetsRouteImport } from './routes/api/assets'
import { Route as ApiAidRouteImport } from './routes/api/aid'
import { Route as AidNewRouteImport } from './routes/aid.new'
import { Route as ProjectsIdEditRouteImport } from './routes/projects.$id.edit'
import { Route as ProcurementSuppliersNewRouteImport } from './routes/procurement.suppliers.new'
import { Route as ProcurementRequestsNewRouteImport } from './routes/procurement.requests.new'
import { Route as ProcurementQuotesNewRouteImport } from './routes/procurement.quotes.new'
import { Route as ProcurementOrdersNewRouteImport } from './routes/procurement.orders.new'
import { Route as InventoryWarehousesNewRouteImport } from './routes/inventory.warehouses.new'
import { Route as InventoryStocktakeNewRouteImport } from './routes/inventory.stocktake.new'
import { Route as InventoryItemsNewRouteImport } from './routes/inventory.items.new'
import { Route as FinanceJournalNewRouteImport } from './routes/finance.journal.new'
import { Route as FinanceBudgetsNewRouteImport } from './routes/finance.budgets.new'
import { Route as FinanceAccountsNewRouteImport } from './routes/finance.accounts.new'
import { Route as DonorsIdEditRouteImport } from './routes/donors.$id.edit'
import { Route as DonationsIdEditRouteImport } from './routes/donations.$id.edit'
import { Route as BeneficiariesIdEditRouteImport } from './routes/beneficiaries.$id.edit'
import { Route as AssetsIdEditRouteImport } from './routes/assets.$id.edit'
import { Route as ApiProcurementSuppliersRouteImport } from './routes/api/procurement/suppliers'
import { Route as ApiProcurementRequestsRouteImport } from './routes/api/procurement/requests'
import { Route as ApiProcurementQuotesRouteImport } from './routes/api/procurement/quotes'
import { Route as ApiProcurementOrdersRouteImport } from './routes/api/procurement/orders'
import { Route as ApiInventoryWarehousesRouteImport } from './routes/api/inventory/warehouses'
import { Route as ApiInventoryStocktakeRouteImport } from './routes/api/inventory/stocktake'
import { Route as ApiInventoryItemsRouteImport } from './routes/api/inventory/items'
import { Route as ApiFinanceStatementsRouteImport } from './routes/api/finance/statements'
import { Route as ApiFinancePeriodsRouteImport } from './routes/api/finance/periods'
import { Route as ApiFinanceLedgerRouteImport } from './routes/api/finance/ledger'
import { Route as ApiFinanceJournalRouteImport } from './routes/api/finance/journal'
import { Route as ApiFinanceCostCentersRouteImport } from './routes/api/finance/cost-centers'
import { Route as ApiFinanceBudgetsRouteImport } from './routes/api/finance/budgets'
import { Route as ApiFinanceAccountsRouteImport } from './routes/api/finance/accounts'
import { Route as AidIdEditRouteImport } from './routes/aid.$id.edit'
import { Route as ProcurementSuppliersIdEditRouteImport } from './routes/procurement.suppliers.$id.edit'
import { Route as ProcurementRequestsIdEditRouteImport } from './routes/procurement.requests.$id.edit'
import { Route as ProcurementQuotesIdEditRouteImport } from './routes/procurement.quotes.$id.edit'
import { Route as ProcurementOrdersIdEditRouteImport } from './routes/procurement.orders.$id.edit'
import { Route as InventoryWarehousesIdEditRouteImport } from './routes/inventory.warehouses.$id.edit'
import { Route as InventoryStocktakeIdEditRouteImport } from './routes/inventory.stocktake.$id.edit'
import { Route as InventoryItemsIdEditRouteImport } from './routes/inventory.items.$id.edit'
import { Route as FinanceJournalIdEditRouteImport } from './routes/finance.journal.$id.edit'
import { Route as FinanceBudgetsIdEditRouteImport } from './routes/finance.budgets.$id.edit'
import { Route as FinanceAccountsIdEditRouteImport } from './routes/finance.accounts.$id.edit'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const EndowmentsRoute = EndowmentsRouteImport.update({
  id: '/endowments',
  path: '/endowments',
  getParentRoute: () => rootRouteImport,
} as any)
const EndowmentReturnsRoute = EndowmentReturnsRouteImport.update({
  id: '/endowment-returns',
  path: '/endowment-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorOrgsRoute = DonorOrgsRouteImport.update({
  id: '/donor-orgs',
  path: '/donor-orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AidRoute = AidRouteImport.update({
  id: '/aid',
  path: '/aid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrgRoute = SettingsOrgRouteImport.update({
  id: '/settings/org',
  path: '/settings/org',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBranchesRoute = SettingsBranchesRouteImport.update({
  id: '/settings/branches',
  path: '/settings/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/settings/backup',
  path: '/settings/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProcurementSuppliersRoute = ProcurementSuppliersRouteImport.update({
  id: '/procurement/suppliers',
  path: '/procurement/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRequestsRoute = ProcurementRequestsRouteImport.update({
  id: '/procurement/requests',
  path: '/procurement/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementQuotesRoute = ProcurementQuotesRouteImport.update({
  id: '/procurement/quotes',
  path: '/procurement/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementOrdersRoute = ProcurementOrdersRouteImport.update({
  id: '/procurement/orders',
  path: '/procurement/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWarehousesRoute = InventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStocktakeRoute = InventoryStocktakeRouteImport.update({
  id: '/inventory/stocktake',
  path: '/inventory/stocktake',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory/items',
  path: '/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceStatementsRoute = FinanceStatementsRouteImport.update({
  id: '/finance/statements',
  path: '/finance/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceLedgerRoute = FinanceLedgerRouteImport.update({
  id: '/finance/ledger',
  path: '/finance/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceJournalRoute = FinanceJournalRouteImport.update({
  id: '/finance/journal',
  path: '/finance/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCostCentersRoute = FinanceCostCentersRouteImport.update({
  id: '/finance/cost-centers',
  path: '/finance/cost-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceClosingRoute = FinanceClosingRouteImport.update({
  id: '/finance/closing',
  path: '/finance/closing',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/finance/budgets',
  path: '/finance/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/finance/accounts',
  path: '/finance/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsNewRoute = DonorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DonorsRoute,
} as any)
const DonorsIdRoute = DonorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DonorsRoute,
} as any)
const DonationsNewRoute = DonationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DonationsRoute,
} as any)
const BeneficiariesNewRoute = BeneficiariesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BeneficiariesRoute,
} as any)
const BeneficiariesIdRoute = BeneficiariesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BeneficiariesRoute,
} as any)
const AssetsNewRoute = AssetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AssetsRoute,
} as any)
const ApiReceiptsRoute = ApiReceiptsRouteImport.update({
  id: '/api/receipts',
  path: '/api/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonorsRoute = ApiDonorsRouteImport.update({
  id: '/api/donors',
  path: '/api/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsRoute = ApiDonationsRouteImport.update({
  id: '/api/donations',
  path: '/api/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeneficiariesRoute = ApiBeneficiariesRouteImport.update({
  id: '/api/beneficiaries',
  path: '/api/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsRoute = ApiAssetsRouteImport.update({
  id: '/api/assets',
  path: '/api/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAidRoute = ApiAidRouteImport.update({
  id: '/api/aid',
  path: '/api/aid',
  getParentRoute: () => rootRouteImport,
} as any)
const AidNewRoute = AidNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AidRoute,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProcurementSuppliersNewRoute = ProcurementSuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProcurementSuppliersRoute,
} as any)
const ProcurementRequestsNewRoute = ProcurementRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProcurementRequestsRoute,
} as any)
const ProcurementQuotesNewRoute = ProcurementQuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProcurementQuotesRoute,
} as any)
const ProcurementOrdersNewRoute = ProcurementOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProcurementOrdersRoute,
} as any)
const InventoryWarehousesNewRoute = InventoryWarehousesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InventoryWarehousesRoute,
} as any)
const InventoryStocktakeNewRoute = InventoryStocktakeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InventoryStocktakeRoute,
} as any)
const InventoryItemsNewRoute = InventoryItemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InventoryItemsRoute,
} as any)
const FinanceJournalNewRoute = FinanceJournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FinanceJournalRoute,
} as any)
const FinanceBudgetsNewRoute = FinanceBudgetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FinanceBudgetsRoute,
} as any)
const FinanceAccountsNewRoute = FinanceAccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FinanceAccountsRoute,
} as any)
const DonorsIdEditRoute = DonorsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DonorsIdRoute,
} as any)
const DonationsIdEditRoute = DonationsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => DonationsRoute,
} as any)
const BeneficiariesIdEditRoute = BeneficiariesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BeneficiariesIdRoute,
} as any)
const AssetsIdEditRoute = AssetsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AssetsRoute,
} as any)
const ApiProcurementSuppliersRoute = ApiProcurementSuppliersRouteImport.update({
  id: '/api/procurement/suppliers',
  path: '/api/procurement/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcurementRequestsRoute = ApiProcurementRequestsRouteImport.update({
  id: '/api/procurement/requests',
  path: '/api/procurement/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcurementQuotesRoute = ApiProcurementQuotesRouteImport.update({
  id: '/api/procurement/quotes',
  path: '/api/procurement/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcurementOrdersRoute = ApiProcurementOrdersRouteImport.update({
  id: '/api/procurement/orders',
  path: '/api/procurement/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryWarehousesRoute = ApiInventoryWarehousesRouteImport.update({
  id: '/api/inventory/warehouses',
  path: '/api/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryStocktakeRoute = ApiInventoryStocktakeRouteImport.update({
  id: '/api/inventory/stocktake',
  path: '/api/inventory/stocktake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryItemsRoute = ApiInventoryItemsRouteImport.update({
  id: '/api/inventory/items',
  path: '/api/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceStatementsRoute = ApiFinanceStatementsRouteImport.update({
  id: '/api/finance/statements',
  path: '/api/finance/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinancePeriodsRoute = ApiFinancePeriodsRouteImport.update({
  id: '/api/finance/periods',
  path: '/api/finance/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceLedgerRoute = ApiFinanceLedgerRouteImport.update({
  id: '/api/finance/ledger',
  path: '/api/finance/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceJournalRoute = ApiFinanceJournalRouteImport.update({
  id: '/api/finance/journal',
  path: '/api/finance/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceCostCentersRoute = ApiFinanceCostCentersRouteImport.update({
  id: '/api/finance/cost-centers',
  path: '/api/finance/cost-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceBudgetsRoute = ApiFinanceBudgetsRouteImport.update({
  id: '/api/finance/budgets',
  path: '/api/finance/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceAccountsRoute = ApiFinanceAccountsRouteImport.update({
  id: '/api/finance/accounts',
  path: '/api/finance/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AidIdEditRoute = AidIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AidRoute,
} as any)
const ProcurementSuppliersIdEditRoute =
  ProcurementSuppliersIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => ProcurementSuppliersRoute,
  } as any)
const ProcurementRequestsIdEditRoute =
  ProcurementRequestsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => ProcurementRequestsRoute,
  } as any)
const ProcurementQuotesIdEditRoute = ProcurementQuotesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => ProcurementQuotesRoute,
} as any)
const ProcurementOrdersIdEditRoute = ProcurementOrdersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => ProcurementOrdersRoute,
} as any)
const InventoryWarehousesIdEditRoute =
  InventoryWarehousesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => InventoryWarehousesRoute,
  } as any)
const InventoryStocktakeIdEditRoute =
  InventoryStocktakeIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => InventoryStocktakeRoute,
  } as any)
const InventoryItemsIdEditRoute = InventoryItemsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => InventoryItemsRoute,
} as any)
const FinanceJournalIdEditRoute = FinanceJournalIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => FinanceJournalRoute,
} as any)
const FinanceBudgetsIdEditRoute = FinanceBudgetsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => FinanceBudgetsRoute,
} as any)
const FinanceAccountsIdEditRoute = FinanceAccountsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => FinanceAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aid': typeof AidRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRouteWithChildren
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRouteWithChildren
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/aid/new': typeof AidNewRoute
  '/api/aid': typeof ApiAidRoute
  '/api/assets': typeof ApiAssetsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/beneficiaries': typeof ApiBeneficiariesRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/donors': typeof ApiDonorsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/receipts': typeof ApiReceiptsRoute
  '/assets/new': typeof AssetsNewRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRouteWithChildren
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/donations/new': typeof DonationsNewRoute
  '/donors/$id': typeof DonorsIdRouteWithChildren
  '/donors/new': typeof DonorsNewRoute
  '/finance/accounts': typeof FinanceAccountsRouteWithChildren
  '/finance/budgets': typeof FinanceBudgetsRouteWithChildren
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRouteWithChildren
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/stocktake': typeof InventoryStocktakeRouteWithChildren
  '/inventory/warehouses': typeof InventoryWarehousesRouteWithChildren
  '/procurement/orders': typeof ProcurementOrdersRouteWithChildren
  '/procurement/quotes': typeof ProcurementQuotesRouteWithChildren
  '/procurement/requests': typeof ProcurementRequestsRouteWithChildren
  '/procurement/suppliers': typeof ProcurementSuppliersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/aid/$id/edit': typeof AidIdEditRoute
  '/api/finance/accounts': typeof ApiFinanceAccountsRoute
  '/api/finance/budgets': typeof ApiFinanceBudgetsRoute
  '/api/finance/cost-centers': typeof ApiFinanceCostCentersRoute
  '/api/finance/journal': typeof ApiFinanceJournalRoute
  '/api/finance/ledger': typeof ApiFinanceLedgerRoute
  '/api/finance/periods': typeof ApiFinancePeriodsRoute
  '/api/finance/statements': typeof ApiFinanceStatementsRoute
  '/api/inventory/items': typeof ApiInventoryItemsRoute
  '/api/inventory/stocktake': typeof ApiInventoryStocktakeRoute
  '/api/inventory/warehouses': typeof ApiInventoryWarehousesRoute
  '/api/procurement/orders': typeof ApiProcurementOrdersRoute
  '/api/procurement/quotes': typeof ApiProcurementQuotesRoute
  '/api/procurement/requests': typeof ApiProcurementRequestsRoute
  '/api/procurement/suppliers': typeof ApiProcurementSuppliersRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/beneficiaries/$id/edit': typeof BeneficiariesIdEditRoute
  '/donations/$id/edit': typeof DonationsIdEditRoute
  '/donors/$id/edit': typeof DonorsIdEditRoute
  '/finance/accounts/new': typeof FinanceAccountsNewRoute
  '/finance/budgets/new': typeof FinanceBudgetsNewRoute
  '/finance/journal/new': typeof FinanceJournalNewRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/inventory/stocktake/new': typeof InventoryStocktakeNewRoute
  '/inventory/warehouses/new': typeof InventoryWarehousesNewRoute
  '/procurement/orders/new': typeof ProcurementOrdersNewRoute
  '/procurement/quotes/new': typeof ProcurementQuotesNewRoute
  '/procurement/requests/new': typeof ProcurementRequestsNewRoute
  '/procurement/suppliers/new': typeof ProcurementSuppliersNewRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/finance/accounts/$id/edit': typeof FinanceAccountsIdEditRoute
  '/finance/budgets/$id/edit': typeof FinanceBudgetsIdEditRoute
  '/finance/journal/$id/edit': typeof FinanceJournalIdEditRoute
  '/inventory/items/$id/edit': typeof InventoryItemsIdEditRoute
  '/inventory/stocktake/$id/edit': typeof InventoryStocktakeIdEditRoute
  '/inventory/warehouses/$id/edit': typeof InventoryWarehousesIdEditRoute
  '/procurement/orders/$id/edit': typeof ProcurementOrdersIdEditRoute
  '/procurement/quotes/$id/edit': typeof ProcurementQuotesIdEditRoute
  '/procurement/requests/$id/edit': typeof ProcurementRequestsIdEditRoute
  '/procurement/suppliers/$id/edit': typeof ProcurementSuppliersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aid': typeof AidRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRouteWithChildren
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRouteWithChildren
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/aid/new': typeof AidNewRoute
  '/api/aid': typeof ApiAidRoute
  '/api/assets': typeof ApiAssetsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/beneficiaries': typeof ApiBeneficiariesRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/donors': typeof ApiDonorsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/receipts': typeof ApiReceiptsRoute
  '/assets/new': typeof AssetsNewRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRouteWithChildren
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/donations/new': typeof DonationsNewRoute
  '/donors/$id': typeof DonorsIdRouteWithChildren
  '/donors/new': typeof DonorsNewRoute
  '/finance/accounts': typeof FinanceAccountsRouteWithChildren
  '/finance/budgets': typeof FinanceBudgetsRouteWithChildren
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRouteWithChildren
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/stocktake': typeof InventoryStocktakeRouteWithChildren
  '/inventory/warehouses': typeof InventoryWarehousesRouteWithChildren
  '/procurement/orders': typeof ProcurementOrdersRouteWithChildren
  '/procurement/quotes': typeof ProcurementQuotesRouteWithChildren
  '/procurement/requests': typeof ProcurementRequestsRouteWithChildren
  '/procurement/suppliers': typeof ProcurementSuppliersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/aid/$id/edit': typeof AidIdEditRoute
  '/api/finance/accounts': typeof ApiFinanceAccountsRoute
  '/api/finance/budgets': typeof ApiFinanceBudgetsRoute
  '/api/finance/cost-centers': typeof ApiFinanceCostCentersRoute
  '/api/finance/journal': typeof ApiFinanceJournalRoute
  '/api/finance/ledger': typeof ApiFinanceLedgerRoute
  '/api/finance/periods': typeof ApiFinancePeriodsRoute
  '/api/finance/statements': typeof ApiFinanceStatementsRoute
  '/api/inventory/items': typeof ApiInventoryItemsRoute
  '/api/inventory/stocktake': typeof ApiInventoryStocktakeRoute
  '/api/inventory/warehouses': typeof ApiInventoryWarehousesRoute
  '/api/procurement/orders': typeof ApiProcurementOrdersRoute
  '/api/procurement/quotes': typeof ApiProcurementQuotesRoute
  '/api/procurement/requests': typeof ApiProcurementRequestsRoute
  '/api/procurement/suppliers': typeof ApiProcurementSuppliersRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/beneficiaries/$id/edit': typeof BeneficiariesIdEditRoute
  '/donations/$id/edit': typeof DonationsIdEditRoute
  '/donors/$id/edit': typeof DonorsIdEditRoute
  '/finance/accounts/new': typeof FinanceAccountsNewRoute
  '/finance/budgets/new': typeof FinanceBudgetsNewRoute
  '/finance/journal/new': typeof FinanceJournalNewRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/inventory/stocktake/new': typeof InventoryStocktakeNewRoute
  '/inventory/warehouses/new': typeof InventoryWarehousesNewRoute
  '/procurement/orders/new': typeof ProcurementOrdersNewRoute
  '/procurement/quotes/new': typeof ProcurementQuotesNewRoute
  '/procurement/requests/new': typeof ProcurementRequestsNewRoute
  '/procurement/suppliers/new': typeof ProcurementSuppliersNewRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/finance/accounts/$id/edit': typeof FinanceAccountsIdEditRoute
  '/finance/budgets/$id/edit': typeof FinanceBudgetsIdEditRoute
  '/finance/journal/$id/edit': typeof FinanceJournalIdEditRoute
  '/inventory/items/$id/edit': typeof InventoryItemsIdEditRoute
  '/inventory/stocktake/$id/edit': typeof InventoryStocktakeIdEditRoute
  '/inventory/warehouses/$id/edit': typeof InventoryWarehousesIdEditRoute
  '/procurement/orders/$id/edit': typeof ProcurementOrdersIdEditRoute
  '/procurement/quotes/$id/edit': typeof ProcurementQuotesIdEditRoute
  '/procurement/requests/$id/edit': typeof ProcurementRequestsIdEditRoute
  '/procurement/suppliers/$id/edit': typeof ProcurementSuppliersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aid': typeof AidRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRouteWithChildren
  '/audit': typeof AuditRoute
  '/beneficiaries': typeof BeneficiariesRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/distribution': typeof DistributionRoute
  '/donations': typeof DonationsRouteWithChildren
  '/donor-orgs': typeof DonorOrgsRoute
  '/donors': typeof DonorsRouteWithChildren
  '/endowment-returns': typeof EndowmentReturnsRoute
  '/endowments': typeof EndowmentsRoute
  '/grants': typeof GrantsRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/workflows': typeof WorkflowsRoute
  '/aid/new': typeof AidNewRoute
  '/api/aid': typeof ApiAidRoute
  '/api/assets': typeof ApiAssetsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/beneficiaries': typeof ApiBeneficiariesRoute
  '/api/donations': typeof ApiDonationsRoute
  '/api/donors': typeof ApiDonorsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/receipts': typeof ApiReceiptsRoute
  '/assets/new': typeof AssetsNewRoute
  '/beneficiaries/$id': typeof BeneficiariesIdRouteWithChildren
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/donations/new': typeof DonationsNewRoute
  '/donors/$id': typeof DonorsIdRouteWithChildren
  '/donors/new': typeof DonorsNewRoute
  '/finance/accounts': typeof FinanceAccountsRouteWithChildren
  '/finance/budgets': typeof FinanceBudgetsRouteWithChildren
  '/finance/closing': typeof FinanceClosingRoute
  '/finance/cost-centers': typeof FinanceCostCentersRoute
  '/finance/journal': typeof FinanceJournalRouteWithChildren
  '/finance/ledger': typeof FinanceLedgerRoute
  '/finance/statements': typeof FinanceStatementsRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/stocktake': typeof InventoryStocktakeRouteWithChildren
  '/inventory/warehouses': typeof InventoryWarehousesRouteWithChildren
  '/procurement/orders': typeof ProcurementOrdersRouteWithChildren
  '/procurement/quotes': typeof ProcurementQuotesRouteWithChildren
  '/procurement/requests': typeof ProcurementRequestsRouteWithChildren
  '/procurement/suppliers': typeof ProcurementSuppliersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/aid/$id/edit': typeof AidIdEditRoute
  '/api/finance/accounts': typeof ApiFinanceAccountsRoute
  '/api/finance/budgets': typeof ApiFinanceBudgetsRoute
  '/api/finance/cost-centers': typeof ApiFinanceCostCentersRoute
  '/api/finance/journal': typeof ApiFinanceJournalRoute
  '/api/finance/ledger': typeof ApiFinanceLedgerRoute
  '/api/finance/periods': typeof ApiFinancePeriodsRoute
  '/api/finance/statements': typeof ApiFinanceStatementsRoute
  '/api/inventory/items': typeof ApiInventoryItemsRoute
  '/api/inventory/stocktake': typeof ApiInventoryStocktakeRoute
  '/api/inventory/warehouses': typeof ApiInventoryWarehousesRoute
  '/api/procurement/orders': typeof ApiProcurementOrdersRoute
  '/api/procurement/quotes': typeof ApiProcurementQuotesRoute
  '/api/procurement/requests': typeof ApiProcurementRequestsRoute
  '/api/procurement/suppliers': typeof ApiProcurementSuppliersRoute
  '/assets/$id/edit': typeof AssetsIdEditRoute
  '/beneficiaries/$id/edit': typeof BeneficiariesIdEditRoute
  '/donations/$id/edit': typeof DonationsIdEditRoute
  '/donors/$id/edit': typeof DonorsIdEditRoute
  '/finance/accounts/new': typeof FinanceAccountsNewRoute
  '/finance/budgets/new': typeof FinanceBudgetsNewRoute
  '/finance/journal/new': typeof FinanceJournalNewRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/inventory/stocktake/new': typeof InventoryStocktakeNewRoute
  '/inventory/warehouses/new': typeof InventoryWarehousesNewRoute
  '/procurement/orders/new': typeof ProcurementOrdersNewRoute
  '/procurement/quotes/new': typeof ProcurementQuotesNewRoute
  '/procurement/requests/new': typeof ProcurementRequestsNewRoute
  '/procurement/suppliers/new': typeof ProcurementSuppliersNewRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/finance/accounts/$id/edit': typeof FinanceAccountsIdEditRoute
  '/finance/budgets/$id/edit': typeof FinanceBudgetsIdEditRoute
  '/finance/journal/$id/edit': typeof FinanceJournalIdEditRoute
  '/inventory/items/$id/edit': typeof InventoryItemsIdEditRoute
  '/inventory/stocktake/$id/edit': typeof InventoryStocktakeIdEditRoute
  '/inventory/warehouses/$id/edit': typeof InventoryWarehousesIdEditRoute
  '/procurement/orders/$id/edit': typeof ProcurementOrdersIdEditRoute
  '/procurement/quotes/$id/edit': typeof ProcurementQuotesIdEditRoute
  '/procurement/requests/$id/edit': typeof ProcurementRequestsIdEditRoute
  '/procurement/suppliers/$id/edit': typeof ProcurementSuppliersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/login'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/aid/new'
    | '/api/aid'
    | '/api/assets'
    | '/api/audit'
    | '/api/auth'
    | '/api/beneficiaries'
    | '/api/donations'
    | '/api/donors'
    | '/api/projects'
    | '/api/receipts'
    | '/assets/new'
    | '/beneficiaries/$id'
    | '/beneficiaries/new'
    | '/donations/new'
    | '/donors/$id'
    | '/donors/new'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
    | '/aid/$id/edit'
    | '/api/finance/accounts'
    | '/api/finance/budgets'
    | '/api/finance/cost-centers'
    | '/api/finance/journal'
    | '/api/finance/ledger'
    | '/api/finance/periods'
    | '/api/finance/statements'
    | '/api/inventory/items'
    | '/api/inventory/stocktake'
    | '/api/inventory/warehouses'
    | '/api/procurement/orders'
    | '/api/procurement/quotes'
    | '/api/procurement/requests'
    | '/api/procurement/suppliers'
    | '/assets/$id/edit'
    | '/beneficiaries/$id/edit'
    | '/donations/$id/edit'
    | '/donors/$id/edit'
    | '/finance/accounts/new'
    | '/finance/budgets/new'
    | '/finance/journal/new'
    | '/inventory/items/new'
    | '/inventory/stocktake/new'
    | '/inventory/warehouses/new'
    | '/procurement/orders/new'
    | '/procurement/quotes/new'
    | '/procurement/requests/new'
    | '/procurement/suppliers/new'
    | '/projects/$id/edit'
    | '/finance/accounts/$id/edit'
    | '/finance/budgets/$id/edit'
    | '/finance/journal/$id/edit'
    | '/inventory/items/$id/edit'
    | '/inventory/stocktake/$id/edit'
    | '/inventory/warehouses/$id/edit'
    | '/procurement/orders/$id/edit'
    | '/procurement/quotes/$id/edit'
    | '/procurement/requests/$id/edit'
    | '/procurement/suppliers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/login'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/aid/new'
    | '/api/aid'
    | '/api/assets'
    | '/api/audit'
    | '/api/auth'
    | '/api/beneficiaries'
    | '/api/donations'
    | '/api/donors'
    | '/api/projects'
    | '/api/receipts'
    | '/assets/new'
    | '/beneficiaries/$id'
    | '/beneficiaries/new'
    | '/donations/new'
    | '/donors/$id'
    | '/donors/new'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
    | '/aid/$id/edit'
    | '/api/finance/accounts'
    | '/api/finance/budgets'
    | '/api/finance/cost-centers'
    | '/api/finance/journal'
    | '/api/finance/ledger'
    | '/api/finance/periods'
    | '/api/finance/statements'
    | '/api/inventory/items'
    | '/api/inventory/stocktake'
    | '/api/inventory/warehouses'
    | '/api/procurement/orders'
    | '/api/procurement/quotes'
    | '/api/procurement/requests'
    | '/api/procurement/suppliers'
    | '/assets/$id/edit'
    | '/beneficiaries/$id/edit'
    | '/donations/$id/edit'
    | '/donors/$id/edit'
    | '/finance/accounts/new'
    | '/finance/budgets/new'
    | '/finance/journal/new'
    | '/inventory/items/new'
    | '/inventory/stocktake/new'
    | '/inventory/warehouses/new'
    | '/procurement/orders/new'
    | '/procurement/quotes/new'
    | '/procurement/requests/new'
    | '/procurement/suppliers/new'
    | '/projects/$id/edit'
    | '/finance/accounts/$id/edit'
    | '/finance/budgets/$id/edit'
    | '/finance/journal/$id/edit'
    | '/inventory/items/$id/edit'
    | '/inventory/stocktake/$id/edit'
    | '/inventory/warehouses/$id/edit'
    | '/procurement/orders/$id/edit'
    | '/procurement/quotes/$id/edit'
    | '/procurement/requests/$id/edit'
    | '/procurement/suppliers/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/aid'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/beneficiaries'
    | '/campaigns'
    | '/distribution'
    | '/donations'
    | '/donor-orgs'
    | '/donors'
    | '/endowment-returns'
    | '/endowments'
    | '/grants'
    | '/hr'
    | '/login'
    | '/meetings'
    | '/memberships'
    | '/notifications'
    | '/permissions'
    | '/projects'
    | '/receipts'
    | '/recurring'
    | '/reports'
    | '/workflows'
    | '/aid/new'
    | '/api/aid'
    | '/api/assets'
    | '/api/audit'
    | '/api/auth'
    | '/api/beneficiaries'
    | '/api/donations'
    | '/api/donors'
    | '/api/projects'
    | '/api/receipts'
    | '/assets/new'
    | '/beneficiaries/$id'
    | '/beneficiaries/new'
    | '/donations/new'
    | '/donors/$id'
    | '/donors/new'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/closing'
    | '/finance/cost-centers'
    | '/finance/journal'
    | '/finance/ledger'
    | '/finance/statements'
    | '/inventory/items'
    | '/inventory/stocktake'
    | '/inventory/warehouses'
    | '/procurement/orders'
    | '/procurement/quotes'
    | '/procurement/requests'
    | '/procurement/suppliers'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/backup'
    | '/settings/branches'
    | '/settings/integrations'
    | '/settings/org'
    | '/settings/system'
    | '/settings/users'
    | '/aid/$id/edit'
    | '/api/finance/accounts'
    | '/api/finance/budgets'
    | '/api/finance/cost-centers'
    | '/api/finance/journal'
    | '/api/finance/ledger'
    | '/api/finance/periods'
    | '/api/finance/statements'
    | '/api/inventory/items'
    | '/api/inventory/stocktake'
    | '/api/inventory/warehouses'
    | '/api/procurement/orders'
    | '/api/procurement/quotes'
    | '/api/procurement/requests'
    | '/api/procurement/suppliers'
    | '/assets/$id/edit'
    | '/beneficiaries/$id/edit'
    | '/donations/$id/edit'
    | '/donors/$id/edit'
    | '/finance/accounts/new'
    | '/finance/budgets/new'
    | '/finance/journal/new'
    | '/inventory/items/new'
    | '/inventory/stocktake/new'
    | '/inventory/warehouses/new'
    | '/procurement/orders/new'
    | '/procurement/quotes/new'
    | '/procurement/requests/new'
    | '/procurement/suppliers/new'
    | '/projects/$id/edit'
    | '/finance/accounts/$id/edit'
    | '/finance/budgets/$id/edit'
    | '/finance/journal/$id/edit'
    | '/inventory/items/$id/edit'
    | '/inventory/stocktake/$id/edit'
    | '/inventory/warehouses/$id/edit'
    | '/procurement/orders/$id/edit'
    | '/procurement/quotes/$id/edit'
    | '/procurement/requests/$id/edit'
    | '/procurement/suppliers/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AidRoute: typeof AidRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  AuditRoute: typeof AuditRoute
  BeneficiariesRoute: typeof BeneficiariesRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  DistributionRoute: typeof DistributionRoute
  DonationsRoute: typeof DonationsRouteWithChildren
  DonorOrgsRoute: typeof DonorOrgsRoute
  DonorsRoute: typeof DonorsRouteWithChildren
  EndowmentReturnsRoute: typeof EndowmentReturnsRoute
  EndowmentsRoute: typeof EndowmentsRoute
  GrantsRoute: typeof GrantsRoute
  HrRoute: typeof HrRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  MembershipsRoute: typeof MembershipsRoute
  NotificationsRoute: typeof NotificationsRoute
  PermissionsRoute: typeof PermissionsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReceiptsRoute: typeof ReceiptsRoute
  RecurringRoute: typeof RecurringRoute
  ReportsRoute: typeof ReportsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ApiAidRoute: typeof ApiAidRoute
  ApiAssetsRoute: typeof ApiAssetsRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiBeneficiariesRoute: typeof ApiBeneficiariesRoute
  ApiDonationsRoute: typeof ApiDonationsRoute
  ApiDonorsRoute: typeof ApiDonorsRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiReceiptsRoute: typeof ApiReceiptsRoute
  FinanceAccountsRoute: typeof FinanceAccountsRouteWithChildren
  FinanceBudgetsRoute: typeof FinanceBudgetsRouteWithChildren
  FinanceClosingRoute: typeof FinanceClosingRoute
  FinanceCostCentersRoute: typeof FinanceCostCentersRoute
  FinanceJournalRoute: typeof FinanceJournalRouteWithChildren
  FinanceLedgerRoute: typeof FinanceLedgerRoute
  FinanceStatementsRoute: typeof FinanceStatementsRoute
  InventoryItemsRoute: typeof InventoryItemsRouteWithChildren
  InventoryStocktakeRoute: typeof InventoryStocktakeRouteWithChildren
  InventoryWarehousesRoute: typeof InventoryWarehousesRouteWithChildren
  ProcurementOrdersRoute: typeof ProcurementOrdersRouteWithChildren
  ProcurementQuotesRoute: typeof ProcurementQuotesRouteWithChildren
  ProcurementRequestsRoute: typeof ProcurementRequestsRouteWithChildren
  ProcurementSuppliersRoute: typeof ProcurementSuppliersRouteWithChildren
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsBranchesRoute: typeof SettingsBranchesRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsOrgRoute: typeof SettingsOrgRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  ApiFinanceAccountsRoute: typeof ApiFinanceAccountsRoute
  ApiFinanceBudgetsRoute: typeof ApiFinanceBudgetsRoute
  ApiFinanceCostCentersRoute: typeof ApiFinanceCostCentersRoute
  ApiFinanceJournalRoute: typeof ApiFinanceJournalRoute
  ApiFinanceLedgerRoute: typeof ApiFinanceLedgerRoute
  ApiFinancePeriodsRoute: typeof ApiFinancePeriodsRoute
  ApiFinanceStatementsRoute: typeof ApiFinanceStatementsRoute
  ApiInventoryItemsRoute: typeof ApiInventoryItemsRoute
  ApiInventoryStocktakeRoute: typeof ApiInventoryStocktakeRoute
  ApiInventoryWarehousesRoute: typeof ApiInventoryWarehousesRoute
  ApiProcurementOrdersRoute: typeof ApiProcurementOrdersRoute
  ApiProcurementQuotesRoute: typeof ApiProcurementQuotesRoute
  ApiProcurementRequestsRoute: typeof ApiProcurementRequestsRoute
  ApiProcurementSuppliersRoute: typeof ApiProcurementSuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endowments': {
      id: '/endowments'
      path: '/endowments'
      fullPath: '/endowments'
      preLoaderRoute: typeof EndowmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endowment-returns': {
      id: '/endowment-returns'
      path: '/endowment-returns'
      fullPath: '/endowment-returns'
      preLoaderRoute: typeof EndowmentReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-orgs': {
      id: '/donor-orgs'
      path: '/donor-orgs'
      fullPath: '/donor-orgs'
      preLoaderRoute: typeof DonorOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aid': {
      id: '/aid'
      path: '/aid'
      fullPath: '/aid'
      preLoaderRoute: typeof AidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/org': {
      id: '/settings/org'
      path: '/settings/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof SettingsOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/branches': {
      id: '/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof SettingsBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/procurement/suppliers': {
      id: '/procurement/suppliers'
      path: '/procurement/suppliers'
      fullPath: '/procurement/suppliers'
      preLoaderRoute: typeof ProcurementSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/requests': {
      id: '/procurement/requests'
      path: '/procurement/requests'
      fullPath: '/procurement/requests'
      preLoaderRoute: typeof ProcurementRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/quotes': {
      id: '/procurement/quotes'
      path: '/procurement/quotes'
      fullPath: '/procurement/quotes'
      preLoaderRoute: typeof ProcurementQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/orders': {
      id: '/procurement/orders'
      path: '/procurement/orders'
      fullPath: '/procurement/orders'
      preLoaderRoute: typeof ProcurementOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/warehouses': {
      id: '/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof InventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stocktake': {
      id: '/inventory/stocktake'
      path: '/inventory/stocktake'
      fullPath: '/inventory/stocktake'
      preLoaderRoute: typeof InventoryStocktakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/statements': {
      id: '/finance/statements'
      path: '/finance/statements'
      fullPath: '/finance/statements'
      preLoaderRoute: typeof FinanceStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/ledger': {
      id: '/finance/ledger'
      path: '/finance/ledger'
      fullPath: '/finance/ledger'
      preLoaderRoute: typeof FinanceLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/journal': {
      id: '/finance/journal'
      path: '/finance/journal'
      fullPath: '/finance/journal'
      preLoaderRoute: typeof FinanceJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/cost-centers': {
      id: '/finance/cost-centers'
      path: '/finance/cost-centers'
      fullPath: '/finance/cost-centers'
      preLoaderRoute: typeof FinanceCostCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/closing': {
      id: '/finance/closing'
      path: '/finance/closing'
      fullPath: '/finance/closing'
      preLoaderRoute: typeof FinanceClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/finance/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/finance/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors/new': {
      id: '/donors/new'
      path: '/new'
      fullPath: '/donors/new'
      preLoaderRoute: typeof DonorsNewRouteImport
      parentRoute: typeof DonorsRoute
    }
    '/donors/$id': {
      id: '/donors/$id'
      path: '/$id'
      fullPath: '/donors/$id'
      preLoaderRoute: typeof DonorsIdRouteImport
      parentRoute: typeof DonorsRoute
    }
    '/donations/new': {
      id: '/donations/new'
      path: '/new'
      fullPath: '/donations/new'
      preLoaderRoute: typeof DonationsNewRouteImport
      parentRoute: typeof DonationsRoute
    }
    '/beneficiaries/new': {
      id: '/beneficiaries/new'
      path: '/new'
      fullPath: '/beneficiaries/new'
      preLoaderRoute: typeof BeneficiariesNewRouteImport
      parentRoute: typeof BeneficiariesRoute
    }
    '/beneficiaries/$id': {
      id: '/beneficiaries/$id'
      path: '/$id'
      fullPath: '/beneficiaries/$id'
      preLoaderRoute: typeof BeneficiariesIdRouteImport
      parentRoute: typeof BeneficiariesRoute
    }
    '/assets/new': {
      id: '/assets/new'
      path: '/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/api/receipts': {
      id: '/api/receipts'
      path: '/api/receipts'
      fullPath: '/api/receipts'
      preLoaderRoute: typeof ApiReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donors': {
      id: '/api/donors'
      path: '/api/donors'
      fullPath: '/api/donors'
      preLoaderRoute: typeof ApiDonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations': {
      id: '/api/donations'
      path: '/api/donations'
      fullPath: '/api/donations'
      preLoaderRoute: typeof ApiDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beneficiaries': {
      id: '/api/beneficiaries'
      path: '/api/beneficiaries'
      fullPath: '/api/beneficiaries'
      preLoaderRoute: typeof ApiBeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets': {
      id: '/api/assets'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aid': {
      id: '/api/aid'
      path: '/api/aid'
      fullPath: '/api/aid'
      preLoaderRoute: typeof ApiAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aid/new': {
      id: '/aid/new'
      path: '/new'
      fullPath: '/aid/new'
      preLoaderRoute: typeof AidNewRouteImport
      parentRoute: typeof AidRoute
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/procurement/suppliers/new': {
      id: '/procurement/suppliers/new'
      path: '/new'
      fullPath: '/procurement/suppliers/new'
      preLoaderRoute: typeof ProcurementSuppliersNewRouteImport
      parentRoute: typeof ProcurementSuppliersRoute
    }
    '/procurement/requests/new': {
      id: '/procurement/requests/new'
      path: '/new'
      fullPath: '/procurement/requests/new'
      preLoaderRoute: typeof ProcurementRequestsNewRouteImport
      parentRoute: typeof ProcurementRequestsRoute
    }
    '/procurement/quotes/new': {
      id: '/procurement/quotes/new'
      path: '/new'
      fullPath: '/procurement/quotes/new'
      preLoaderRoute: typeof ProcurementQuotesNewRouteImport
      parentRoute: typeof ProcurementQuotesRoute
    }
    '/procurement/orders/new': {
      id: '/procurement/orders/new'
      path: '/new'
      fullPath: '/procurement/orders/new'
      preLoaderRoute: typeof ProcurementOrdersNewRouteImport
      parentRoute: typeof ProcurementOrdersRoute
    }
    '/inventory/warehouses/new': {
      id: '/inventory/warehouses/new'
      path: '/new'
      fullPath: '/inventory/warehouses/new'
      preLoaderRoute: typeof InventoryWarehousesNewRouteImport
      parentRoute: typeof InventoryWarehousesRoute
    }
    '/inventory/stocktake/new': {
      id: '/inventory/stocktake/new'
      path: '/new'
      fullPath: '/inventory/stocktake/new'
      preLoaderRoute: typeof InventoryStocktakeNewRouteImport
      parentRoute: typeof InventoryStocktakeRoute
    }
    '/inventory/items/new': {
      id: '/inventory/items/new'
      path: '/new'
      fullPath: '/inventory/items/new'
      preLoaderRoute: typeof InventoryItemsNewRouteImport
      parentRoute: typeof InventoryItemsRoute
    }
    '/finance/journal/new': {
      id: '/finance/journal/new'
      path: '/new'
      fullPath: '/finance/journal/new'
      preLoaderRoute: typeof FinanceJournalNewRouteImport
      parentRoute: typeof FinanceJournalRoute
    }
    '/finance/budgets/new': {
      id: '/finance/budgets/new'
      path: '/new'
      fullPath: '/finance/budgets/new'
      preLoaderRoute: typeof FinanceBudgetsNewRouteImport
      parentRoute: typeof FinanceBudgetsRoute
    }
    '/finance/accounts/new': {
      id: '/finance/accounts/new'
      path: '/new'
      fullPath: '/finance/accounts/new'
      preLoaderRoute: typeof FinanceAccountsNewRouteImport
      parentRoute: typeof FinanceAccountsRoute
    }
    '/donors/$id/edit': {
      id: '/donors/$id/edit'
      path: '/edit'
      fullPath: '/donors/$id/edit'
      preLoaderRoute: typeof DonorsIdEditRouteImport
      parentRoute: typeof DonorsIdRoute
    }
    '/donations/$id/edit': {
      id: '/donations/$id/edit'
      path: '/$id/edit'
      fullPath: '/donations/$id/edit'
      preLoaderRoute: typeof DonationsIdEditRouteImport
      parentRoute: typeof DonationsRoute
    }
    '/beneficiaries/$id/edit': {
      id: '/beneficiaries/$id/edit'
      path: '/edit'
      fullPath: '/beneficiaries/$id/edit'
      preLoaderRoute: typeof BeneficiariesIdEditRouteImport
      parentRoute: typeof BeneficiariesIdRoute
    }
    '/assets/$id/edit': {
      id: '/assets/$id/edit'
      path: '/$id/edit'
      fullPath: '/assets/$id/edit'
      preLoaderRoute: typeof AssetsIdEditRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/api/procurement/suppliers': {
      id: '/api/procurement/suppliers'
      path: '/api/procurement/suppliers'
      fullPath: '/api/procurement/suppliers'
      preLoaderRoute: typeof ApiProcurementSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/procurement/requests': {
      id: '/api/procurement/requests'
      path: '/api/procurement/requests'
      fullPath: '/api/procurement/requests'
      preLoaderRoute: typeof ApiProcurementRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/procurement/quotes': {
      id: '/api/procurement/quotes'
      path: '/api/procurement/quotes'
      fullPath: '/api/procurement/quotes'
      preLoaderRoute: typeof ApiProcurementQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/procurement/orders': {
      id: '/api/procurement/orders'
      path: '/api/procurement/orders'
      fullPath: '/api/procurement/orders'
      preLoaderRoute: typeof ApiProcurementOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/warehouses': {
      id: '/api/inventory/warehouses'
      path: '/api/inventory/warehouses'
      fullPath: '/api/inventory/warehouses'
      preLoaderRoute: typeof ApiInventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/stocktake': {
      id: '/api/inventory/stocktake'
      path: '/api/inventory/stocktake'
      fullPath: '/api/inventory/stocktake'
      preLoaderRoute: typeof ApiInventoryStocktakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/items': {
      id: '/api/inventory/items'
      path: '/api/inventory/items'
      fullPath: '/api/inventory/items'
      preLoaderRoute: typeof ApiInventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/statements': {
      id: '/api/finance/statements'
      path: '/api/finance/statements'
      fullPath: '/api/finance/statements'
      preLoaderRoute: typeof ApiFinanceStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/periods': {
      id: '/api/finance/periods'
      path: '/api/finance/periods'
      fullPath: '/api/finance/periods'
      preLoaderRoute: typeof ApiFinancePeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/ledger': {
      id: '/api/finance/ledger'
      path: '/api/finance/ledger'
      fullPath: '/api/finance/ledger'
      preLoaderRoute: typeof ApiFinanceLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/journal': {
      id: '/api/finance/journal'
      path: '/api/finance/journal'
      fullPath: '/api/finance/journal'
      preLoaderRoute: typeof ApiFinanceJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/cost-centers': {
      id: '/api/finance/cost-centers'
      path: '/api/finance/cost-centers'
      fullPath: '/api/finance/cost-centers'
      preLoaderRoute: typeof ApiFinanceCostCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/budgets': {
      id: '/api/finance/budgets'
      path: '/api/finance/budgets'
      fullPath: '/api/finance/budgets'
      preLoaderRoute: typeof ApiFinanceBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/accounts': {
      id: '/api/finance/accounts'
      path: '/api/finance/accounts'
      fullPath: '/api/finance/accounts'
      preLoaderRoute: typeof ApiFinanceAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aid/$id/edit': {
      id: '/aid/$id/edit'
      path: '/$id/edit'
      fullPath: '/aid/$id/edit'
      preLoaderRoute: typeof AidIdEditRouteImport
      parentRoute: typeof AidRoute
    }
    '/procurement/suppliers/$id/edit': {
      id: '/procurement/suppliers/$id/edit'
      path: '/$id/edit'
      fullPath: '/procurement/suppliers/$id/edit'
      preLoaderRoute: typeof ProcurementSuppliersIdEditRouteImport
      parentRoute: typeof ProcurementSuppliersRoute
    }
    '/procurement/requests/$id/edit': {
      id: '/procurement/requests/$id/edit'
      path: '/$id/edit'
      fullPath: '/procurement/requests/$id/edit'
      preLoaderRoute: typeof ProcurementRequestsIdEditRouteImport
      parentRoute: typeof ProcurementRequestsRoute
    }
    '/procurement/quotes/$id/edit': {
      id: '/procurement/quotes/$id/edit'
      path: '/$id/edit'
      fullPath: '/procurement/quotes/$id/edit'
      preLoaderRoute: typeof ProcurementQuotesIdEditRouteImport
      parentRoute: typeof ProcurementQuotesRoute
    }
    '/procurement/orders/$id/edit': {
      id: '/procurement/orders/$id/edit'
      path: '/$id/edit'
      fullPath: '/procurement/orders/$id/edit'
      preLoaderRoute: typeof ProcurementOrdersIdEditRouteImport
      parentRoute: typeof ProcurementOrdersRoute
    }
    '/inventory/warehouses/$id/edit': {
      id: '/inventory/warehouses/$id/edit'
      path: '/$id/edit'
      fullPath: '/inventory/warehouses/$id/edit'
      preLoaderRoute: typeof InventoryWarehousesIdEditRouteImport
      parentRoute: typeof InventoryWarehousesRoute
    }
    '/inventory/stocktake/$id/edit': {
      id: '/inventory/stocktake/$id/edit'
      path: '/$id/edit'
      fullPath: '/inventory/stocktake/$id/edit'
      preLoaderRoute: typeof InventoryStocktakeIdEditRouteImport
      parentRoute: typeof InventoryStocktakeRoute
    }
    '/inventory/items/$id/edit': {
      id: '/inventory/items/$id/edit'
      path: '/$id/edit'
      fullPath: '/inventory/items/$id/edit'
      preLoaderRoute: typeof InventoryItemsIdEditRouteImport
      parentRoute: typeof InventoryItemsRoute
    }
    '/finance/journal/$id/edit': {
      id: '/finance/journal/$id/edit'
      path: '/$id/edit'
      fullPath: '/finance/journal/$id/edit'
      preLoaderRoute: typeof FinanceJournalIdEditRouteImport
      parentRoute: typeof FinanceJournalRoute
    }
    '/finance/budgets/$id/edit': {
      id: '/finance/budgets/$id/edit'
      path: '/$id/edit'
      fullPath: '/finance/budgets/$id/edit'
      preLoaderRoute: typeof FinanceBudgetsIdEditRouteImport
      parentRoute: typeof FinanceBudgetsRoute
    }
    '/finance/accounts/$id/edit': {
      id: '/finance/accounts/$id/edit'
      path: '/$id/edit'
      fullPath: '/finance/accounts/$id/edit'
      preLoaderRoute: typeof FinanceAccountsIdEditRouteImport
      parentRoute: typeof FinanceAccountsRoute
    }
  }
}

interface AidRouteChildren {
  AidNewRoute: typeof AidNewRoute
  AidIdEditRoute: typeof AidIdEditRoute
}

const AidRouteChildren: AidRouteChildren = {
  AidNewRoute: AidNewRoute,
  AidIdEditRoute: AidIdEditRoute,
}

const AidRouteWithChildren = AidRoute._addFileChildren(AidRouteChildren)

interface AssetsRouteChildren {
  AssetsNewRoute: typeof AssetsNewRoute
  AssetsIdEditRoute: typeof AssetsIdEditRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsNewRoute: AssetsNewRoute,
  AssetsIdEditRoute: AssetsIdEditRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface BeneficiariesIdRouteChildren {
  BeneficiariesIdEditRoute: typeof BeneficiariesIdEditRoute
}

const BeneficiariesIdRouteChildren: BeneficiariesIdRouteChildren = {
  BeneficiariesIdEditRoute: BeneficiariesIdEditRoute,
}

const BeneficiariesIdRouteWithChildren = BeneficiariesIdRoute._addFileChildren(
  BeneficiariesIdRouteChildren,
)

interface BeneficiariesRouteChildren {
  BeneficiariesIdRoute: typeof BeneficiariesIdRouteWithChildren
  BeneficiariesNewRoute: typeof BeneficiariesNewRoute
}

const BeneficiariesRouteChildren: BeneficiariesRouteChildren = {
  BeneficiariesIdRoute: BeneficiariesIdRouteWithChildren,
  BeneficiariesNewRoute: BeneficiariesNewRoute,
}

const BeneficiariesRouteWithChildren = BeneficiariesRoute._addFileChildren(
  BeneficiariesRouteChildren,
)

interface DonationsRouteChildren {
  DonationsNewRoute: typeof DonationsNewRoute
  DonationsIdEditRoute: typeof DonationsIdEditRoute
}

const DonationsRouteChildren: DonationsRouteChildren = {
  DonationsNewRoute: DonationsNewRoute,
  DonationsIdEditRoute: DonationsIdEditRoute,
}

const DonationsRouteWithChildren = DonationsRoute._addFileChildren(
  DonationsRouteChildren,
)

interface DonorsIdRouteChildren {
  DonorsIdEditRoute: typeof DonorsIdEditRoute
}

const DonorsIdRouteChildren: DonorsIdRouteChildren = {
  DonorsIdEditRoute: DonorsIdEditRoute,
}

const DonorsIdRouteWithChildren = DonorsIdRoute._addFileChildren(
  DonorsIdRouteChildren,
)

interface DonorsRouteChildren {
  DonorsIdRoute: typeof DonorsIdRouteWithChildren
  DonorsNewRoute: typeof DonorsNewRoute
}

const DonorsRouteChildren: DonorsRouteChildren = {
  DonorsIdRoute: DonorsIdRouteWithChildren,
  DonorsNewRoute: DonorsNewRoute,
}

const DonorsRouteWithChildren =
  DonorsRoute._addFileChildren(DonorsRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface FinanceAccountsRouteChildren {
  FinanceAccountsNewRoute: typeof FinanceAccountsNewRoute
  FinanceAccountsIdEditRoute: typeof FinanceAccountsIdEditRoute
}

const FinanceAccountsRouteChildren: FinanceAccountsRouteChildren = {
  FinanceAccountsNewRoute: FinanceAccountsNewRoute,
  FinanceAccountsIdEditRoute: FinanceAccountsIdEditRoute,
}

const FinanceAccountsRouteWithChildren = FinanceAccountsRoute._addFileChildren(
  FinanceAccountsRouteChildren,
)

interface FinanceBudgetsRouteChildren {
  FinanceBudgetsNewRoute: typeof FinanceBudgetsNewRoute
  FinanceBudgetsIdEditRoute: typeof FinanceBudgetsIdEditRoute
}

const FinanceBudgetsRouteChildren: FinanceBudgetsRouteChildren = {
  FinanceBudgetsNewRoute: FinanceBudgetsNewRoute,
  FinanceBudgetsIdEditRoute: FinanceBudgetsIdEditRoute,
}

const FinanceBudgetsRouteWithChildren = FinanceBudgetsRoute._addFileChildren(
  FinanceBudgetsRouteChildren,
)

interface FinanceJournalRouteChildren {
  FinanceJournalNewRoute: typeof FinanceJournalNewRoute
  FinanceJournalIdEditRoute: typeof FinanceJournalIdEditRoute
}

const FinanceJournalRouteChildren: FinanceJournalRouteChildren = {
  FinanceJournalNewRoute: FinanceJournalNewRoute,
  FinanceJournalIdEditRoute: FinanceJournalIdEditRoute,
}

const FinanceJournalRouteWithChildren = FinanceJournalRoute._addFileChildren(
  FinanceJournalRouteChildren,
)

interface InventoryItemsRouteChildren {
  InventoryItemsNewRoute: typeof InventoryItemsNewRoute
  InventoryItemsIdEditRoute: typeof InventoryItemsIdEditRoute
}

const InventoryItemsRouteChildren: InventoryItemsRouteChildren = {
  InventoryItemsNewRoute: InventoryItemsNewRoute,
  InventoryItemsIdEditRoute: InventoryItemsIdEditRoute,
}

const InventoryItemsRouteWithChildren = InventoryItemsRoute._addFileChildren(
  InventoryItemsRouteChildren,
)

interface InventoryStocktakeRouteChildren {
  InventoryStocktakeNewRoute: typeof InventoryStocktakeNewRoute
  InventoryStocktakeIdEditRoute: typeof InventoryStocktakeIdEditRoute
}

const InventoryStocktakeRouteChildren: InventoryStocktakeRouteChildren = {
  InventoryStocktakeNewRoute: InventoryStocktakeNewRoute,
  InventoryStocktakeIdEditRoute: InventoryStocktakeIdEditRoute,
}

const InventoryStocktakeRouteWithChildren =
  InventoryStocktakeRoute._addFileChildren(InventoryStocktakeRouteChildren)

interface InventoryWarehousesRouteChildren {
  InventoryWarehousesNewRoute: typeof InventoryWarehousesNewRoute
  InventoryWarehousesIdEditRoute: typeof InventoryWarehousesIdEditRoute
}

const InventoryWarehousesRouteChildren: InventoryWarehousesRouteChildren = {
  InventoryWarehousesNewRoute: InventoryWarehousesNewRoute,
  InventoryWarehousesIdEditRoute: InventoryWarehousesIdEditRoute,
}

const InventoryWarehousesRouteWithChildren =
  InventoryWarehousesRoute._addFileChildren(InventoryWarehousesRouteChildren)

interface ProcurementOrdersRouteChildren {
  ProcurementOrdersNewRoute: typeof ProcurementOrdersNewRoute
  ProcurementOrdersIdEditRoute: typeof ProcurementOrdersIdEditRoute
}

const ProcurementOrdersRouteChildren: ProcurementOrdersRouteChildren = {
  ProcurementOrdersNewRoute: ProcurementOrdersNewRoute,
  ProcurementOrdersIdEditRoute: ProcurementOrdersIdEditRoute,
}

const ProcurementOrdersRouteWithChildren =
  ProcurementOrdersRoute._addFileChildren(ProcurementOrdersRouteChildren)

interface ProcurementQuotesRouteChildren {
  ProcurementQuotesNewRoute: typeof ProcurementQuotesNewRoute
  ProcurementQuotesIdEditRoute: typeof ProcurementQuotesIdEditRoute
}

const ProcurementQuotesRouteChildren: ProcurementQuotesRouteChildren = {
  ProcurementQuotesNewRoute: ProcurementQuotesNewRoute,
  ProcurementQuotesIdEditRoute: ProcurementQuotesIdEditRoute,
}

const ProcurementQuotesRouteWithChildren =
  ProcurementQuotesRoute._addFileChildren(ProcurementQuotesRouteChildren)

interface ProcurementRequestsRouteChildren {
  ProcurementRequestsNewRoute: typeof ProcurementRequestsNewRoute
  ProcurementRequestsIdEditRoute: typeof ProcurementRequestsIdEditRoute
}

const ProcurementRequestsRouteChildren: ProcurementRequestsRouteChildren = {
  ProcurementRequestsNewRoute: ProcurementRequestsNewRoute,
  ProcurementRequestsIdEditRoute: ProcurementRequestsIdEditRoute,
}

const ProcurementRequestsRouteWithChildren =
  ProcurementRequestsRoute._addFileChildren(ProcurementRequestsRouteChildren)

interface ProcurementSuppliersRouteChildren {
  ProcurementSuppliersNewRoute: typeof ProcurementSuppliersNewRoute
  ProcurementSuppliersIdEditRoute: typeof ProcurementSuppliersIdEditRoute
}

const ProcurementSuppliersRouteChildren: ProcurementSuppliersRouteChildren = {
  ProcurementSuppliersNewRoute: ProcurementSuppliersNewRoute,
  ProcurementSuppliersIdEditRoute: ProcurementSuppliersIdEditRoute,
}

const ProcurementSuppliersRouteWithChildren =
  ProcurementSuppliersRoute._addFileChildren(ProcurementSuppliersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AidRoute: AidRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  AssetsRoute: AssetsRouteWithChildren,
  AuditRoute: AuditRoute,
  BeneficiariesRoute: BeneficiariesRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  DistributionRoute: DistributionRoute,
  DonationsRoute: DonationsRouteWithChildren,
  DonorOrgsRoute: DonorOrgsRoute,
  DonorsRoute: DonorsRouteWithChildren,
  EndowmentReturnsRoute: EndowmentReturnsRoute,
  EndowmentsRoute: EndowmentsRoute,
  GrantsRoute: GrantsRoute,
  HrRoute: HrRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  MembershipsRoute: MembershipsRoute,
  NotificationsRoute: NotificationsRoute,
  PermissionsRoute: PermissionsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReceiptsRoute: ReceiptsRoute,
  RecurringRoute: RecurringRoute,
  ReportsRoute: ReportsRoute,
  WorkflowsRoute: WorkflowsRoute,
  ApiAidRoute: ApiAidRoute,
  ApiAssetsRoute: ApiAssetsRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiBeneficiariesRoute: ApiBeneficiariesRoute,
  ApiDonationsRoute: ApiDonationsRoute,
  ApiDonorsRoute: ApiDonorsRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiReceiptsRoute: ApiReceiptsRoute,
  FinanceAccountsRoute: FinanceAccountsRouteWithChildren,
  FinanceBudgetsRoute: FinanceBudgetsRouteWithChildren,
  FinanceClosingRoute: FinanceClosingRoute,
  FinanceCostCentersRoute: FinanceCostCentersRoute,
  FinanceJournalRoute: FinanceJournalRouteWithChildren,
  FinanceLedgerRoute: FinanceLedgerRoute,
  FinanceStatementsRoute: FinanceStatementsRoute,
  InventoryItemsRoute: InventoryItemsRouteWithChildren,
  InventoryStocktakeRoute: InventoryStocktakeRouteWithChildren,
  InventoryWarehousesRoute: InventoryWarehousesRouteWithChildren,
  ProcurementOrdersRoute: ProcurementOrdersRouteWithChildren,
  ProcurementQuotesRoute: ProcurementQuotesRouteWithChildren,
  ProcurementRequestsRoute: ProcurementRequestsRouteWithChildren,
  ProcurementSuppliersRoute: ProcurementSuppliersRouteWithChildren,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsBranchesRoute: SettingsBranchesRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsOrgRoute: SettingsOrgRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  ApiFinanceAccountsRoute: ApiFinanceAccountsRoute,
  ApiFinanceBudgetsRoute: ApiFinanceBudgetsRoute,
  ApiFinanceCostCentersRoute: ApiFinanceCostCentersRoute,
  ApiFinanceJournalRoute: ApiFinanceJournalRoute,
  ApiFinanceLedgerRoute: ApiFinanceLedgerRoute,
  ApiFinancePeriodsRoute: ApiFinancePeriodsRoute,
  ApiFinanceStatementsRoute: ApiFinanceStatementsRoute,
  ApiInventoryItemsRoute: ApiInventoryItemsRoute,
  ApiInventoryStocktakeRoute: ApiInventoryStocktakeRoute,
  ApiInventoryWarehousesRoute: ApiInventoryWarehousesRoute,
  ApiProcurementOrdersRoute: ApiProcurementOrdersRoute,
  ApiProcurementQuotesRoute: ApiProcurementQuotesRoute,
  ApiProcurementRequestsRoute: ApiProcurementRequestsRoute,
  ApiProcurementSuppliersRoute: ApiProcurementSuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
